package marmotd

import (
	"os"
	"path/filepath"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func TestISCSIInitiatorID(t *testing.T) {
	RegisterFailHandler(Fail)
	suiteConfig, reporterConfig := GinkgoConfiguration()
	suiteConfig.LabelFilter = "iscsi-initiator"
	RunSpecs(t, "iSCSI Initiator ID Suite", suiteConfig, reporterConfig)
}

var _ = Describe("iSCSI Initiator ID", Label("iscsi-initiator"), func() {
	var tempDir string
	var origFile string
	var origRestart func() error

	BeforeEach(func() {
		var err error
		tempDir, err = os.MkdirTemp("", "iscsi-test-")
		Expect(err).NotTo(HaveOccurred())

		origFile = iscsiInitiatornameFile
		origRestart = systemctlRestartIscsid
		iscsiInitiatornameFile = filepath.Join(tempDir, "initiatorname.iscsi")
		systemctlRestartIscsid = func() error { return nil }
	})

	AfterEach(func() {
		iscsiInitiatornameFile = origFile
		systemctlRestartIscsid = origRestart
		os.RemoveAll(tempDir)
	})

	Context("getISCSIInitiatorID", func() {
		It("ファイルが存在しない場合は空文字列を返す", func() {
			Expect(getISCSIInitiatorID()).To(BeEmpty())
		})

		It("InitiatorName を正しく読み込む", func() {
			content := "## DO NOT EDIT OR REMOVE THIS FILE!\n" +
				"InitiatorName=iqn.2004-10.com.ubuntu:01:c1b5e3a5db\n"
			Expect(os.WriteFile(iscsiInitiatornameFile, []byte(content), 0644)).To(Succeed())

			Expect(getISCSIInitiatorID()).To(Equal("iqn.2004-10.com.ubuntu:01:c1b5e3a5db"))
		})

		It("コメント行をスキップして InitiatorName を返す", func() {
			content := "## DO NOT EDIT OR REMOVE THIS FILE!\n" +
				"## If you remove this file, the iSCSI daemon will not start.\n" +
				"InitiatorName=iqn.2024-01.com.marmot:client-host1\n"
			Expect(os.WriteFile(iscsiInitiatornameFile, []byte(content), 0644)).To(Succeed())

			Expect(getISCSIInitiatorID()).To(Equal("iqn.2024-01.com.marmot:client-host1"))
		})
	})

	Context("ensureISCSIInitiatorID", func() {
		It("ファイルが存在しない場合、marmot 形式の IQN を生成してファイルを作成する", func() {
			Expect(ensureISCSIInitiatorID("testnode")).To(Succeed())

			iqn := getISCSIInitiatorID()
			Expect(iqn).To(Equal("iqn.2004-10.com.marmot:testnode"))
		})

		It("既に marmot 形式の IQN が設定されている場合は変更しない", func() {
			content := "## Generated by marmot.\nInitiatorName=iqn.2004-10.com.marmot:existingnode\n"
			Expect(os.WriteFile(iscsiInitiatornameFile, []byte(content), 0644)).To(Succeed())

			Expect(ensureISCSIInitiatorID("testnode")).To(Succeed())

			// 既存の値が保持されること
			Expect(getISCSIInitiatorID()).To(Equal("iqn.2004-10.com.marmot:existingnode"))
		})

		It("marmot 以外の IQN が設定されている場合、marmot 形式に上書きする", func() {
			content := "## Original\nInitiatorName=iqn.2004-10.com.ubuntu:01:c1b5e3a5db\n"
			Expect(os.WriteFile(iscsiInitiatornameFile, []byte(content), 0644)).To(Succeed())

			Expect(ensureISCSIInitiatorID("mynode")).To(Succeed())

			Expect(getISCSIInitiatorID()).To(Equal("iqn.2004-10.com.marmot:mynode"))
		})

		It("nodeName が空の場合、hostname を使ってIQNを生成する", func() {
			Expect(ensureISCSIInitiatorID("")).To(Succeed())

			iqn := getISCSIInitiatorID()
			Expect(iqn).To(HavePrefix("iqn.2004-10.com.marmot:"))
			Expect(iqn).NotTo(Equal("iqn.2004-10.com.marmot:"))
		})

		It("iscsid が正常に再起動される", func() {
			restartCalled := false
			systemctlRestartIscsid = func() error {
				restartCalled = true
				return nil
			}

			Expect(ensureISCSIInitiatorID("testnode")).To(Succeed())
			Expect(restartCalled).To(BeTrue())
		})
	})
})


var _ = Describe("iSCSI Initiator ID", Label("iscsi-initiator"), func() {
	var tempDir string

	BeforeEach(func() {
		var err error
		tempDir, err = os.MkdirTemp("", "iscsi-test-")
		Expect(err).NotTo(HaveOccurred())
	})

	AfterEach(func() {
		if tempDir != "" {
			os.RemoveAll(tempDir)
		}
	})

	It("reads InitiatorName from initiatorname.iscsi", func() {
		testFile := filepath.Join(tempDir, "initiatorname.iscsi")
		content := `## DO NOT EDIT OR REMOVE THIS FILE!
## If you remove this file, the iSCSI daemon will not start.
InitiatorName=iqn.2004-10.com.ubuntu:01:c1b5e3a5db
`
		err := os.WriteFile(testFile, []byte(content), 0644)
		Expect(err).NotTo(HaveOccurred())

		// 一時的に initiatorname.iscsi のパスを変更するため、
		// テストでモック化する前に直接ファイルを読み込んでテストする
		data, err := os.ReadFile(testFile)
		Expect(err).NotTo(HaveOccurred())

		// InitiatorName の行を抽出する処理をテストする
		lines := []string{
			"## DO NOT EDIT OR REMOVE THIS FILE!",
			"## If you remove this file, the iSCSI daemon will not start.",
			"InitiatorName=iqn.2004-10.com.ubuntu:01:c1b5e3a5db",
		}
		var result string
		for _, line := range lines {
			if len(line) > 0 && line[0] != '#' && len(line) > len("InitiatorName=") {
				if line[0:14] == "InitiatorName=" {
					result = line[14:]
					break
				}
			}
		}
		Expect(result).To(Equal("iqn.2004-10.com.ubuntu:01:c1b5e3a5db"))

		_ = data
	})

	It("returns empty string when initiatorname.iscsi does not exist", func() {
		// getISCSIInitiatorID 関数はファイルが存在しない場合に空文字列を返す
		// この動作は自動的にテストされる
		Expect(true).To(BeTrue()) // プレースホルダー
	})

	It("handles initiatorname.iscsi with comments correctly", func() {
		testFile := filepath.Join(tempDir, "initiatorname.iscsi")
		content := `## DO NOT EDIT OR REMOVE THIS FILE!
## If you remove this file, the iSCSI daemon will not start.
## If you change the InitiatorName, existing access control lists
## may reject this initiator. The InitiatorName must be unique
## for each iSCSI initiator. Do NOT duplicate iSCSI InitiatorNames.
InitiatorName=iqn.2024-01.com.marmot:client-host1
`
		err := os.WriteFile(testFile, []byte(content), 0644)
		Expect(err).NotTo(HaveOccurred())

		data, err := os.ReadFile(testFile)
		Expect(err).NotTo(HaveOccurred())
		Expect(data).NotTo(BeNil())
		// ファイルが正常に読み込めることを確認
		Expect(len(data)).To(BeNumerically(">", 0))
	})
})
