.PHONY: test
test:
	#find ~/ -name "ginkgo" -type f -executable 
	#go mod tidy
	#go install github.com/onsi/ginkgo/v2/ginkgo@latest
	/home/ubuntu/go/bin/ginkgo -v --race --focus-file mock-server_test.go
	
