---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
stringData:
  # Required for statically and dynamically provisioned volumes
  # The userID must not include the "client." prefix!
  userID: fsuser1
  userKey: AQDpp45qeHR8FBAAgHJA+Gdy9PFKkzIM5r+AGA==

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
