GO = go
PROGRAM = marmot-lb-agent

.PHONY: all $(PROGRAM)
all: $(PROGRAM)

TAG := $(shell type ..\..\TAG)
BINDIR = ..\..\dist\marmot-v$(TAG)

$(PROGRAM):
	@echo $(BINDIR)
	if not exist "$(BINDIR)" mkdir "$(BINDIR)"
	$(GO) build -o "$(BINDIR)\$@.exe" $^

.PHONY: clean
clean:
	if exist "$(BINDIR)" rmdir /s /q "$(BINDIR)"

.PHONY: install
install:
	copy "$(BINDIR)\$(PROGRAM).exe" "%USERPROFILE%\AppData\Local\bin\"
