#
# 最小構成のGitLab
#
domain: labo.local
cluster_name: test

## Hypervisor type
hypervisor: kvm

## 仮想マシンイメージの設定
image_template_path: /home/images
image_default_path:  /home/images

qcow2_image: ubuntu20.04-amd.qcow2
os_variant:  ubuntu20.04

## Cluster Network
private_ip_subnet: 172.16.0.0/16
public_ip_subnet:  192.168.1.0/24

### Network device and config
net_dev_default: enp1s0
net_dev_private: enp2s0
net_dev_public:  enp3s0

public_ip_gw:  192.168.1.1
public_ip_dns: 192.168.1.8

### Virtual Machine Spec
vm_spec:
  - name: "master1"
    cpu: 1
    memory: 1024
    private_ip:  "172.16.99.101"
    public_ip:   "192.168.1.10"
    storage:
    - name: repo_data1
      size: 10
      path: /stg2
    vm_host: auto
    playbook: install.yaml
    comment: "Test Server"
  - name: "node1"
    cpu: 1
    memory: 1024
    private_ip:  "172.16.99.102"
    storage:
    - name: repo_data1
      size: 10
      path: /stg2
    vm_host: auto
    playbook: install.yaml
    comment: "Test Server"
  - name: "node2"
    cpu: 1
    memory: 1024
    private_ip:  "172.16.99.103"
    storage:
    - name: repo_data1
      size: 10
      path: /stg2
    vm_host: auto
    playbook: install.yaml
    comment: "Test Server"


