hv_spec:
  - name:     "hv1"
    port:     8750
    cpu:      12
    free_cpu: 12
    ram:      64
    free_ram: 64
    ip_addr:  "10.1.0.11"
    storage_pool:
    - vg: "vg1"
      type: "ssd"
    - vg: "vg2"
      type: "nvme"
    - vg: "vg3"
      type: "hdd"

image_template:
  - name: "ubuntu20.04"
    volumegroup: "vg1"
    logicalvolume: "lv01"
  - name: "ubuntu18.04"
    volumegroup: "vg1"
    logicalvolume: "lv02"
  - name: "ubuntu22.04"
    volumegroup: "vg1"
    logicalvolume: "lv03"

#
# シリアル番号管理
#
seqno:
  - name: "LVOS"
    start: 100
    step:  1
  - name: "LVDATA"
    start: 100
    step:  1
  - name: "VM"
    start: 100
    step:  1
