hv_spec:
  - name:     "hv3"
    cpu:      64
    free_cpu: 64
    ram:      128
    free_ram: 128
    ip_addr:  "10.1.0.13"
    storage_pool:
    - vg: "vg1"
      type: "ssd"
    - vg: "vg2"
      type: "nvme"
    - vg: "vg3"
      type: "hdd"

  - name:     "hv4"
    cpu:      64
    free_cpu: 64
    ram:      128
    free_ram: 128
    ip_addr:  "10.1.0.14"
    storage_pool:
    - vg: "vg1"
      type: "ssd"
    - vg: "vg2"
      type: "nvme"
    - vg: "vg3"
      type: "hdd"

image_template:
  - name: "ubuntu20.04"
    volumegroup: "vg1"
    logicalvolume: "lv01"
  - name: "ubuntu18.04"
    volumegroup: "vg1"
    logicalvolume: "lv02"

#
# シリアル番号管理
#
seqno:
  - name: "LVOS"
    start: 500
    step:  1
  - name: "LVDATA"
    start: 500
    step:  1
  - name: "VM"
    start: 500
    step:  1
