openapi: "3.0.3"
info:
  version: 0.0.5
  title: REST API of Marmot Server
servers:
  - url: http://0.0.0.0:{port}{basePath}
    description: Marmot Server API
    variables:
      port:
        enum:
          - "8080"
        default: "8080"
      basePath:
        default: /api/v1
        description: Base path for the API
tags:
  - name: user
  - name: version
paths:
  /version:
    get:
      summary: "Get Version"
      operationId: getVersion
      tags:
        - version
      responses:
        "200":
          description: Get Marmot Server Version
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
  /ping:
    get:
      summary: "Alive"
      operationId: replyPing
      tags:
        - alive
      responses:
        "200":
          description: Check Marmot Server is Alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReplyMessage"
  /volume:
    post:
      summary: "Create Volume"
      operationId: createVolume
      tags:
        - storage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Volume"
      responses:
        "200":
          description: Created the Volume
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "List Volumes"
      operationId: listVolumes
      tags:
        - storage
      responses:
        "200":
          description: List of Volumes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Volume"
  /volume/{volumeId}:
    get:
      summary: "Info for a specific volume"
      operationId: showVolumeById
      tags:
        - storage
      parameters:
        - name: volumeId
          in: path
          required: true
          description: The id of the volume to retrieve
          schema:
            type: string
    put:
      summary: "Update Volume"
      operationId: updateVolumeById
      tags:
        - storage
      parameters:
        - name: volumeId
          in: path
          required: true
          description: The id of the volume to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Volume"
      responses:
        "200":
          description: Updated the Volume
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete Volume"
      operationId: deleteVolumeById
      tags:
        - storage
      parameters:
        - name: volumeId
          in: path
          required: true
          description: The id of the volume to delete
          schema:
            type: string
      responses:
        "200":
          description: Deleted the Volume
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /server:
    post:
      summary: "Create Virtual Server"
      description: |
        Create a new virtual server. The virtual server specifications are specified in the request body.
        If the virtual server is successfully created, the information of the created virtual server is returned in the response.
        The virtual server is then automatically started.
        The virtual server specifications include CPU, memory, storage, network settings, and more.
        If an error occurs during virtual server creation, an appropriate error message is returned.
      operationId: createServer
      tags:
        - server
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Server"
      responses:
        "201":
          description: "Successfully created and started the virtual server."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        default:
          description: "An error occurred."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "Get Server Information"
      description: |
        Retrieve information about existing virtual servers. A list of virtual servers is returned in the response.
        Each virtual server's information includes server ID, status, resource usage, and more.
        If no virtual servers exist or an error occurs while retrieving information, an appropriate error message is returned.
      operationId: getServers
      tags:
        - server
      responses:
        "200":
          description: "Successfully retrieved the list of servers."
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Servers"
        default:
          description: "An error occurred."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /server/{id}:
      get:
        summary: "Get particular server Information"
        operationId: getServerById
        tags:
          - server
        parameters:
          - name: id
            in: path
            required: true
            description: The ID identifies the server.
            schema:
              type: string
        responses:
          "200":
            description: "Successfully retrieved the server information."
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Server"
          default:
            description: "An error occurred."
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
      put:
        summary: "Update Server Information by Id"
        operationId: updateServerById
        tags:
          - server
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the server to update
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Server"
        responses:
          "200":
            description: Updated the Server
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
      delete:
        summary: "Delete Server"
        operationId: deleteServerById
        tags:
          - server
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the server to delete
            schema:
              type: string
        responses:
          "200":
            description: Deleted the Server
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"

components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    Version:
      type: object
      required:
        - clientVersion
      properties:
        serverVersion:
          type: string
        clientVersion:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Success:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        message:
          type: string
    ReplyMessage:
      type: object
      properties:
        message:
          type: string
          example: "ok"
      required:
        - message
    Volume:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        type:
          type: string
        kind:
          type: string
        key:
          type: string
        name:
          type: string
        volumeGroup:
          type: string
        logicalVolume:
          type: string
        size:
          type: integer
          format: int
        path:
          type: string
        status:
          type: integer
          format: int
        cTime:
          type: string
          format: date-time
        mTime:
          type: string
          format: date-time
        osVariant:
          type: string
        comment:
          type: string
        persistent:
          type: boolean
    Network:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        uuid:
          type: string
        networkname:
          type: string
        ethernet:
          type: string
        mac:
          type: string
        dhcp4:
          type: boolean
        dhcp6:
          type: boolean
        address:
          type: string
        netmask:
          type: string
        nameservers:
          type: object
          $ref: "#/components/schemas/Nameservers"
        routes:
          type: array
          maxItems: 6
          items:
            $ref: "#/components/schemas/Route"
        portgroup:
          type: string
        vlans:
          type: array
          maxItems: 4
          items:
            type: integer
            format: uint
    Nameservers:
      type: object
      properties:
        addresses:
          type: array
          maxItems: 4
          items:
            type: string
        search:
          type: array
          maxItems: 4
          items:
            type: string
    Route:
      type: object
      properties:
        to:
          type: string
        via:
          type: string
    Servers:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Server"
    Server:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        uuid:
          type: string
        name:
          type: string
        instanceName:
          type: string
        clusterName:
          type: string
        key:
          type: string
        cTime:
          type: string
          format: date-time
        sTime:
          type: string
          format: date-time
        status:
          type: integer
          format: int
        cpu:
          type: integer
          format: int
        memory:
          type: integer
          format: int
        Network:
          type: array
          maxItems: 10
          items:
            $ref: "#/components/schemas/Network"
        Storage:
          type: array
          maxItems: 10
          items:
            $ref: "#/components/schemas/Volume"
        playbook:
          type: string
        comment:
          type: string
        osLv:
          type: string
        osVg:
          type: string
        osVariant:
          type: string
        bootVolume:
          $ref: "#/components/schemas/Volume"