// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Auth defines model for Auth.
type Auth struct {
	PublicKey    *string `json:"publicKey,omitempty"`
	RootPassword *string `json:"rootPassword,omitempty"`
	Url          *string `json:"url,omitempty"`
	User         *string `json:"user,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// IPAddress defines model for IPAddress.
type IPAddress struct {
	HostId    *string `json:"HostId,omitempty"`
	IPAddress *string `json:"IPAddress,omitempty"`
	Netmask   *string `json:"Netmask,omitempty"`
	NetworkId *string `json:"NetworkId,omitempty"`
}

// IPNetwork defines model for IPNetwork.
type IPNetwork struct {
	AddressMaskLen   *string `json:"AddressMaskLen,omitempty"`
	EndAddress       *string `json:"EndAddress,omitempty"`
	Gateway          *string `json:"Gateway,omitempty"`
	Id               string  `json:"Id"`
	Netmask          *string `json:"Netmask,omitempty"`
	Netmasklen       *int    `json:"Netmasklen,omitempty"`
	NetworkAddress   *string `json:"NetworkAddress,omitempty"`
	StartAddress     *string `json:"StartAddress,omitempty"`
	VirtualNetworkId *string `json:"virtualNetworkId,omitempty"`
}

// Image defines model for Image.
type Image struct {
	Metadata *Metadata  `json:"Metadata,omitempty"`
	Spec     *ImageSpec `json:"Spec,omitempty"`
	Status   *Status    `json:"Status,omitempty"`
	Id       string     `json:"id"`
}

// ImageSpec defines model for ImageSpec.
type ImageSpec struct {
	Kind          *string `json:"kind,omitempty"`
	LogicalVolume *string `json:"logicalVolume,omitempty"`
	LvPath        *string `json:"lvPath,omitempty"`
	Qcow2Path     *string `json:"qcow2Path,omitempty"`
	Size          *int    `json:"size,omitempty"`
	SourceUrl     *string `json:"source_url,omitempty"`
	Type          *string `json:"type,omitempty"`
	VolumeGroup   *string `json:"volumeGroup,omitempty"`
}

// Job defines model for Job.
type Job struct {
	Metadata *Metadata `json:"Metadata,omitempty"`
	Spec     *JobSpec  `json:"Spec,omitempty"`
	Status   *Status   `json:"Status,omitempty"`
	Id       string    `json:"id"`
}

// JobSpec defines model for JobSpec.
type JobSpec struct {
	Command     *[]string  `json:"Command,omitempty"`
	ExitCode    *int       `json:"ExitCode,omitempty"`
	FinishTime  *time.Time `json:"FinishTime,omitempty"`
	MaxTime     *time.Time `json:"MaxTime,omitempty"`
	RequestTime *time.Time `json:"RequestTime,omitempty"`
	StartTime   *time.Time `json:"StartTime,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Comment      *string                 `json:"comment,omitempty"`
	Id           *string                 `json:"id,omitempty"`
	InstanceName *string                 `json:"instanceName,omitempty"`
	Key          *string                 `json:"key,omitempty"`
	Labels       *map[string]interface{} `json:"labels,omitempty"`
	Name         *string                 `json:"name,omitempty"`
	Uuid         *string                 `json:"uuid,omitempty"`
}

// Nameservers defines model for Nameservers.
type Nameservers struct {
	Addresses *[]string `json:"addresses,omitempty"`
	Search    *[]string `json:"search,omitempty"`
}

// NetworkInterface defines model for NetworkInterface.
type NetworkInterface struct {
	Address     *string      `json:"address,omitempty"`
	Dhcp4       *bool        `json:"dhcp4,omitempty"`
	Dhcp6       *bool        `json:"dhcp6,omitempty"`
	Ethernet    *string      `json:"ethernet,omitempty"`
	IpGateway   *string      `json:"ipGateway,omitempty"`
	IpNetworkId *string      `json:"ipNetworkId,omitempty"`
	Mac         *string      `json:"mac,omitempty"`
	Nameservers *Nameservers `json:"nameservers,omitempty"`
	Netmask     *string      `json:"netmask,omitempty"`
	Netmasklen  *int         `json:"netmasklen,omitempty"`
	Networkid   string       `json:"networkid"`
	Networkname string       `json:"networkname"`
	Portgroup   *string      `json:"portgroup,omitempty"`
	Routes      *[]Route     `json:"routes,omitempty"`
	Uuid        *string      `json:"uuid,omitempty"`
	Vlans       *[]uint      `json:"vlans,omitempty"`
}

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}

// ReplyMessage defines model for ReplyMessage.
type ReplyMessage struct {
	Message string `json:"message"`
}

// Route defines model for Route.
type Route struct {
	To  *string `json:"to,omitempty"`
	Via *string `json:"via,omitempty"`
}

// Server defines model for Server.
type Server struct {
	Metadata *Metadata   `json:"Metadata,omitempty"`
	Spec     *ServerSpec `json:"Spec,omitempty"`
	Status   *Status     `json:"Status,omitempty"`
	Id       string      `json:"id"`
}

// ServerSpec defines model for ServerSpec.
type ServerSpec struct {
	NetworkInterface *[]NetworkInterface `json:"NetworkInterface,omitempty"`
	Storage          *[]Volume           `json:"Storage,omitempty"`
	Auth             *Auth               `json:"auth,omitempty"`
	BootVolume       *Volume             `json:"bootVolume,omitempty"`
	Cpu              *int                `json:"cpu,omitempty"`
	Memory           *int                `json:"memory,omitempty"`
	OsLv             *string             `json:"osLv,omitempty"`
	OsVariant        *string             `json:"osVariant,omitempty"`
	OsVg             *string             `json:"osVg,omitempty"`
}

// Servers defines model for Servers.
type Servers = []Server

// Status defines model for Status.
type Status struct {
	CreationTimeStamp   *time.Time `json:"creationTimeStamp,omitempty"`
	DeletionTimeStamp   *time.Time `json:"deletionTimeStamp,omitempty"`
	LastUpdateTimeStamp *time.Time `json:"lastUpdateTimeStamp,omitempty"`
	Message             *string    `json:"message,omitempty"`
	Status              *string    `json:"status,omitempty"`
	StatusCode          int        `json:"statusCode"`
}

// Success defines model for Success.
type Success struct {
	Id      string  `json:"id"`
	Message *string `json:"message,omitempty"`
}

// Version defines model for Version.
type Version struct {
	ClientVersion string  `json:"clientVersion"`
	ServerVersion *string `json:"serverVersion,omitempty"`
}

// VirtualNetwork defines model for VirtualNetwork.
type VirtualNetwork struct {
	Metadata *Metadata           `json:"Metadata,omitempty"`
	Spec     *VirtualNetworkSpec `json:"Spec,omitempty"`
	Status   *Status             `json:"Status,omitempty"`
	Id       string              `json:"id"`
}

// VirtualNetworkSpec defines model for VirtualNetworkSpec.
type VirtualNetworkSpec struct {
	BridgeName       *string `json:"bridgeName,omitempty"`
	Dhcp             *bool   `json:"dhcp,omitempty"`
	DhcpEndAddress   *string `json:"dhcpEndAddress,omitempty"`
	DhcpStartAddress *string `json:"dhcpStartAddress,omitempty"`
	ForwardMode      *string `json:"forwardMode,omitempty"`
	IPNetworkAddress *string `json:"iPNetworkAddress,omitempty"`
	IpAddress        *string `json:"ipAddress,omitempty"`
	IpNetworkId      *string `json:"ipNetworkId,omitempty"`
	MacAddress       *string `json:"macAddress,omitempty"`
	Nat              *bool   `json:"nat,omitempty"`
	Netmask          *string `json:"netmask,omitempty"`
	Stp              *bool   `json:"stp,omitempty"`
}

// VolSpec defines model for VolSpec.
type VolSpec struct {
	Kind          *string `json:"kind,omitempty"`
	LogicalVolume *string `json:"logicalVolume,omitempty"`
	OsVariant     *string `json:"osVariant,omitempty"`
	Path          *string `json:"path,omitempty"`
	Persistent    *bool   `json:"persistent,omitempty"`
	Size          *int    `json:"size,omitempty"`
	Type          *string `json:"type,omitempty"`
	VolumeGroup   *string `json:"volumeGroup,omitempty"`
}

// Volume defines model for Volume.
type Volume struct {
	Metadata *Metadata `json:"Metadata,omitempty"`
	Spec     *VolSpec  `json:"Spec,omitempty"`
	Status   *Status   `json:"Status,omitempty"`
	Id       string    `json:"id"`
}

// ApiCreateImageJSONRequestBody defines body for ApiCreateImage for application/json ContentType.
type ApiCreateImageJSONRequestBody = Image

// ApiUpdateImageByIdJSONRequestBody defines body for ApiUpdateImageById for application/json ContentType.
type ApiUpdateImageByIdJSONRequestBody = Image

// ApiCreateNetworkJSONRequestBody defines body for ApiCreateNetwork for application/json ContentType.
type ApiCreateNetworkJSONRequestBody = VirtualNetwork

// ApiUpdateNetworkByIdJSONRequestBody defines body for ApiUpdateNetworkById for application/json ContentType.
type ApiUpdateNetworkByIdJSONRequestBody = VirtualNetwork

// ApiCreateServerJSONRequestBody defines body for ApiCreateServer for application/json ContentType.
type ApiCreateServerJSONRequestBody = Server

// ApiMakeImageEntryFromRunningVMByIdJSONRequestBody defines body for ApiMakeImageEntryFromRunningVMById for application/json ContentType.
type ApiMakeImageEntryFromRunningVMByIdJSONRequestBody = Image

// ApiUpdateServerByIdJSONRequestBody defines body for ApiUpdateServerById for application/json ContentType.
type ApiUpdateServerByIdJSONRequestBody = Server

// ApiCreateVolumeJSONRequestBody defines body for ApiCreateVolume for application/json ContentType.
type ApiCreateVolumeJSONRequestBody = Volume

// ApiUpdateVolumeByIdJSONRequestBody defines body for ApiUpdateVolumeById for application/json ContentType.
type ApiUpdateVolumeByIdJSONRequestBody = Volume

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Images
	// (GET /image)
	ApiGetImages(ctx echo.Context) error
	// Create Image
	// (POST /image)
	ApiCreateImage(ctx echo.Context) error
	// Delete Image
	// (DELETE /image/{id})
	ApiDeleteImageById(ctx echo.Context, id string) error
	// Info for a specific image
	// (GET /image/{id})
	ApiGetImageById(ctx echo.Context, id string) error
	// Update Image
	// (PUT /image/{id})
	ApiUpdateImageById(ctx echo.Context, id string) error
	// List all assigned IP Networks
	// (GET /ipnetwork)
	ApiListIpNetworks(ctx echo.Context) error
	// Get assigned IP addresses for a specific IP network
	// (GET /ipnetwork/{id}/addresses)
	ApiGetIpAddressesByNetwork(ctx echo.Context, id string) error
	// Get Network Information
	// (GET /network)
	ApiGetNetworks(ctx echo.Context) error
	// Create Virtual Network
	// (POST /network)
	ApiCreateNetwork(ctx echo.Context) error
	// Delete Virtual Network
	// (DELETE /network/{id})
	ApiDeleteNetworkById(ctx echo.Context, id string) error
	// Get particular virtual network Information
	// (GET /network/{id})
	ApiGetNetworkById(ctx echo.Context, id string) error
	// Update Virtual Network Information by Id
	// (PUT /network/{id})
	ApiUpdateNetworkById(ctx echo.Context, id string) error
	// Get IP networks for a virtual network
	// (GET /network/{id}/ipnetworks)
	ApiGetNetworkIpNetworks(ctx echo.Context, id string) error
	// Alive
	// (GET /ping)
	ApiReplyPing(ctx echo.Context) error
	// Get Server Information
	// (GET /server)
	ApiGetServers(ctx echo.Context) error
	// Create Virtual Server
	// (POST /server)
	ApiCreateServer(ctx echo.Context) error
	// Delete Server
	// (DELETE /server/{id})
	ApiDeleteServerById(ctx echo.Context, id string) error
	// Get particular server Information
	// (GET /server/{id})
	ApiGetServerById(ctx echo.Context, id string) error
	// Create image from Server Object by Id
	// (POST /server/{id})
	ApiMakeImageEntryFromRunningVMById(ctx echo.Context, id string) error
	// Update Server Information by Id
	// (PUT /server/{id})
	ApiUpdateServerById(ctx echo.Context, id string) error
	// Get Version
	// (GET /version)
	ApiGetVersion(ctx echo.Context) error
	// List Volumes
	// (GET /volume)
	ApiListVolumes(ctx echo.Context) error
	// Create Volume
	// (POST /volume)
	ApiCreateVolume(ctx echo.Context) error
	// Delete Volume
	// (DELETE /volume/{volumeId})
	ApiDeleteVolumeById(ctx echo.Context, volumeId string) error
	// Info for a specific volume
	// (GET /volume/{volumeId})
	ApiShowVolumeById(ctx echo.Context, volumeId string) error
	// Update Volume
	// (PUT /volume/{volumeId})
	ApiUpdateVolumeById(ctx echo.Context, volumeId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ApiGetImages converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetImages(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetImages(ctx)
	return err
}

// ApiCreateImage converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateImage(ctx)
	return err
}

// ApiDeleteImageById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteImageById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteImageById(ctx, id)
	return err
}

// ApiGetImageById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetImageById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetImageById(ctx, id)
	return err
}

// ApiUpdateImageById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateImageById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateImageById(ctx, id)
	return err
}

// ApiListIpNetworks converts echo context to params.
func (w *ServerInterfaceWrapper) ApiListIpNetworks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiListIpNetworks(ctx)
	return err
}

// ApiGetIpAddressesByNetwork converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetIpAddressesByNetwork(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetIpAddressesByNetwork(ctx, id)
	return err
}

// ApiGetNetworks converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetNetworks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetNetworks(ctx)
	return err
}

// ApiCreateNetwork converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateNetwork(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateNetwork(ctx)
	return err
}

// ApiDeleteNetworkById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteNetworkById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteNetworkById(ctx, id)
	return err
}

// ApiGetNetworkById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetNetworkById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetNetworkById(ctx, id)
	return err
}

// ApiUpdateNetworkById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateNetworkById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateNetworkById(ctx, id)
	return err
}

// ApiGetNetworkIpNetworks converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetNetworkIpNetworks(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetNetworkIpNetworks(ctx, id)
	return err
}

// ApiReplyPing converts echo context to params.
func (w *ServerInterfaceWrapper) ApiReplyPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiReplyPing(ctx)
	return err
}

// ApiGetServers converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetServers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetServers(ctx)
	return err
}

// ApiCreateServer converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateServer(ctx)
	return err
}

// ApiDeleteServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteServerById(ctx, id)
	return err
}

// ApiGetServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetServerById(ctx, id)
	return err
}

// ApiMakeImageEntryFromRunningVMById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiMakeImageEntryFromRunningVMById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiMakeImageEntryFromRunningVMById(ctx, id)
	return err
}

// ApiUpdateServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateServerById(ctx, id)
	return err
}

// ApiGetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetVersion(ctx)
	return err
}

// ApiListVolumes converts echo context to params.
func (w *ServerInterfaceWrapper) ApiListVolumes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiListVolumes(ctx)
	return err
}

// ApiCreateVolume converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateVolume(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateVolume(ctx)
	return err
}

// ApiDeleteVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteVolumeById(ctx, volumeId)
	return err
}

// ApiShowVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiShowVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiShowVolumeById(ctx, volumeId)
	return err
}

// ApiUpdateVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateVolumeById(ctx, volumeId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/image", wrapper.ApiGetImages)
	router.POST(baseURL+"/image", wrapper.ApiCreateImage)
	router.DELETE(baseURL+"/image/:id", wrapper.ApiDeleteImageById)
	router.GET(baseURL+"/image/:id", wrapper.ApiGetImageById)
	router.PUT(baseURL+"/image/:id", wrapper.ApiUpdateImageById)
	router.GET(baseURL+"/ipnetwork", wrapper.ApiListIpNetworks)
	router.GET(baseURL+"/ipnetwork/:id/addresses", wrapper.ApiGetIpAddressesByNetwork)
	router.GET(baseURL+"/network", wrapper.ApiGetNetworks)
	router.POST(baseURL+"/network", wrapper.ApiCreateNetwork)
	router.DELETE(baseURL+"/network/:id", wrapper.ApiDeleteNetworkById)
	router.GET(baseURL+"/network/:id", wrapper.ApiGetNetworkById)
	router.PUT(baseURL+"/network/:id", wrapper.ApiUpdateNetworkById)
	router.GET(baseURL+"/network/:id/ipnetworks", wrapper.ApiGetNetworkIpNetworks)
	router.GET(baseURL+"/ping", wrapper.ApiReplyPing)
	router.GET(baseURL+"/server", wrapper.ApiGetServers)
	router.POST(baseURL+"/server", wrapper.ApiCreateServer)
	router.DELETE(baseURL+"/server/:id", wrapper.ApiDeleteServerById)
	router.GET(baseURL+"/server/:id", wrapper.ApiGetServerById)
	router.POST(baseURL+"/server/:id", wrapper.ApiMakeImageEntryFromRunningVMById)
	router.PUT(baseURL+"/server/:id", wrapper.ApiUpdateServerById)
	router.GET(baseURL+"/version", wrapper.ApiGetVersion)
	router.GET(baseURL+"/volume", wrapper.ApiListVolumes)
	router.POST(baseURL+"/volume", wrapper.ApiCreateVolume)
	router.DELETE(baseURL+"/volume/:volumeId", wrapper.ApiDeleteVolumeById)
	router.GET(baseURL+"/volume/:volumeId", wrapper.ApiShowVolumeById)
	router.PUT(baseURL+"/volume/:volumeId", wrapper.ApiUpdateVolumeById)

}
