// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for VirtualNetworkSpecOverlayMode.
const (
	Geneve VirtualNetworkSpecOverlayMode = "geneve"
	None   VirtualNetworkSpecOverlayMode = "none"
	Vxlan  VirtualNetworkSpecOverlayMode = "vxlan"
)

// Valid indicates whether the value is a known member of the VirtualNetworkSpecOverlayMode enum.
func (e VirtualNetworkSpecOverlayMode) Valid() bool {
	switch e {
	case Geneve:
		return true
	case None:
		return true
	case Vxlan:
		return true
	default:
		return false
	}
}

// Defines values for VirtualNetworkSpecPeerPolicy.
const (
	Auto   VirtualNetworkSpecPeerPolicy = "auto"
	Manual VirtualNetworkSpecPeerPolicy = "manual"
)

// Valid indicates whether the value is a known member of the VirtualNetworkSpecPeerPolicy enum.
func (e VirtualNetworkSpecPeerPolicy) Valid() bool {
	switch e {
	case Auto:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// ApplicationLoadBalancer defines model for ApplicationLoadBalancer.
type ApplicationLoadBalancer struct {
	ApiVersion string                      `json:"apiVersion" yaml:"apiVersion"`
	Kind       string                      `json:"kind" yaml:"kind"`
	Metadata   Metadata                    `json:"metadata" yaml:"metadata"`
	Spec       ApplicationLoadBalancerSpec `json:"spec" yaml:"spec"`
	Status     *Status                     `json:"status,omitempty" yaml:"status,omitempty"`
}

// ApplicationLoadBalancerHealthCheck defines model for ApplicationLoadBalancerHealthCheck.
type ApplicationLoadBalancerHealthCheck struct {
	Enabled            bool   `json:"enabled" yaml:"enabled"`
	IntervalSeconds    int    `json:"intervalSeconds,omitempty" yaml:"intervalSeconds,omitempty"`
	Path               string `json:"path,omitempty" yaml:"path,omitempty"`
	TimeoutSeconds     int    `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty"`
	UnhealthyThreshold int    `json:"unhealthyThreshold,omitempty" yaml:"unhealthyThreshold,omitempty"`
}

// ApplicationLoadBalancerLabelSelector defines model for ApplicationLoadBalancerLabelSelector.
type ApplicationLoadBalancerLabelSelector struct {
	MatchLabels map[string]string `json:"matchLabels,omitempty" yaml:"matchLabels,omitempty"`
}

// ApplicationLoadBalancerListener defines model for ApplicationLoadBalancerListener.
type ApplicationLoadBalancerListener struct {
	BackendPort            int                                  `json:"backendPort" yaml:"backendPort"`
	BackendSelector        ApplicationLoadBalancerLabelSelector `json:"backendSelector" yaml:"backendSelector"`
	HealthCheck            *ApplicationLoadBalancerHealthCheck  `json:"healthCheck,omitempty" yaml:"healthCheck,omitempty"`
	LoadBalancingAlgorithm string                               `json:"loadBalancingAlgorithm,omitempty" yaml:"loadBalancingAlgorithm,omitempty"`
	Name                   string                               `json:"name" yaml:"name"`
	Protocol               string                               `json:"protocol" yaml:"protocol"`
	SessionPersistence     *ApplicationLoadBalancerPersistence  `json:"sessionPersistence,omitempty" yaml:"sessionPersistence,omitempty"`
	VipPort                int                                  `json:"vipPort" yaml:"vipPort"`
}

// ApplicationLoadBalancerPersistence defines model for ApplicationLoadBalancerPersistence.
type ApplicationLoadBalancerPersistence struct {
	CookieName string `json:"cookieName,omitempty" yaml:"cookieName,omitempty"`
	Enabled    bool   `json:"enabled" yaml:"enabled"`
}

// ApplicationLoadBalancerSpec defines model for ApplicationLoadBalancerSpec.
type ApplicationLoadBalancerSpec struct {
	BindPublicIpAddress    string                            `json:"bindPublicIpAddress" yaml:"bindPublicIpAddress"`
	InternalVirtualNetwork string                            `json:"internalVirtualNetwork" yaml:"internalVirtualNetwork"`
	Listeners              []ApplicationLoadBalancerListener `json:"listeners" yaml:"listeners"`

	// RemoteCIDR Source CIDR allowed to access the load balancer. Empty means allow all.
	RemoteCIDR string `json:"remoteCIDR,omitempty" yaml:"remoteCIDR,omitempty"`
}

// Auth defines model for Auth.
type Auth struct {
	PublicKey    *string `json:"publicKey,omitempty" yaml:"publicKey,omitempty"`
	RootPassword *string `json:"rootPassword,omitempty" yaml:"rootPassword,omitempty"`
	Url          *string `json:"url,omitempty" yaml:"url,omitempty"`
	User         *string `json:"user,omitempty" yaml:"user,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}

// Gateway defines model for Gateway.
type Gateway struct {
	ApiVersion string      `json:"apiVersion" yaml:"apiVersion"`
	Kind       string      `json:"kind" yaml:"kind"`
	Metadata   Metadata    `json:"metadata" yaml:"metadata"`
	Spec       GatewaySpec `json:"spec" yaml:"spec"`
	Status     *Status     `json:"status,omitempty" yaml:"status,omitempty"`
}

// GatewaySpec defines model for GatewaySpec.
type GatewaySpec struct {
	BindPublicIpAddress    string `json:"bindPublicIpAddress" yaml:"bindPublicIpAddress"`
	InternalServerName     string `json:"internalServerName" yaml:"internalServerName"`
	InternalVirtualNetwork string `json:"internalVirtualNetwork" yaml:"internalVirtualNetwork"`

	// RemoteCIDR Source CIDR allowed to access gateway forwarding.
	RemoteCIDR string `json:"remoteCIDR,omitempty" yaml:"remoteCIDR,omitempty"`

	// RemoteCIDRs Source CIDR list allowed to access gateway forwarding. Empty means allow all.
	RemoteCIDRs []string `json:"remoteCIDRs,omitempty" yaml:"remoteCIDRs,omitempty"`
	ServerPorts []string `json:"serverPorts" yaml:"serverPorts"`
}

// HostAllocation defines model for HostAllocation.
type HostAllocation struct {
	AllocatedCpuCores *int `json:"allocatedCpuCores,omitempty" yaml:"allocatedCpuCores,omitempty"`
	AllocatedMemoryMB *int `json:"allocatedMemoryMB,omitempty" yaml:"allocatedMemoryMB,omitempty"`
	RunningVMs        *int `json:"runningVMs,omitempty" yaml:"runningVMs,omitempty"`
	StoppedVMs        *int `json:"stoppedVMs,omitempty" yaml:"stoppedVMs,omitempty"`
	TotalVMs          *int `json:"totalVMs,omitempty" yaml:"totalVMs,omitempty"`
	VirtualNetworks   *int `json:"virtualNetworks,omitempty" yaml:"virtualNetworks,omitempty"`
}

// HostCapacity defines model for HostCapacity.
type HostCapacity struct {
	CpuCores          *int      `json:"cpuCores,omitempty" yaml:"cpuCores,omitempty"`
	DiskCapacityGB    *int      `json:"diskCapacityGB,omitempty" yaml:"diskCapacityGB,omitempty"`
	DiskCount         *int      `json:"diskCount,omitempty" yaml:"diskCount,omitempty"`
	MemoryMB          *int      `json:"memoryMB,omitempty" yaml:"memoryMB,omitempty"`
	NetworkInterfaces *[]string `json:"networkInterfaces,omitempty" yaml:"networkInterfaces,omitempty"`
}

// HostStatus defines model for HostStatus.
type HostStatus struct {
	Allocation  *HostAllocation `json:"allocation,omitempty" yaml:"allocation,omitempty"`
	Capacity    *HostCapacity   `json:"capacity,omitempty" yaml:"capacity,omitempty"`
	HostId      *string         `json:"hostId,omitempty" yaml:"hostId,omitempty"`
	InitiatorId *string         `json:"initiatorId,omitempty" yaml:"initiatorId,omitempty"`
	IpAddress   *string         `json:"ipAddress,omitempty" yaml:"ipAddress,omitempty"`
	IscsiServer *bool           `json:"iscsiServer,omitempty" yaml:"iscsiServer,omitempty"`
	LastUpdated *time.Time      `json:"lastUpdated,omitempty" yaml:"lastUpdated,omitempty"`
	NodeName    *string         `json:"nodeName,omitempty" yaml:"nodeName,omitempty"`
}

// IPAddress defines model for IPAddress.
type IPAddress struct {
	HostId    *string `json:"hostId,omitempty" yaml:"hostId,omitempty"`
	IpAddress string  `json:"ipAddress" yaml:"ipAddress"`
	Netmask   *string `json:"netmask,omitempty" yaml:"netmask,omitempty"`
	NetworkId *string `json:"networkId,omitempty" yaml:"networkId,omitempty"`
}

// IPNetwork defines model for IPNetwork.
type IPNetwork struct {
	AddressMaskLen   *string `json:"addressMaskLen,omitempty" yaml:"addressMaskLen,omitempty"`
	EndAddress       *string `json:"endAddress,omitempty" yaml:"endAddress,omitempty"`
	Gateway          *string `json:"gateway,omitempty" yaml:"gateway,omitempty"`
	Id               string  `json:"id" yaml:"id"`
	Netmask          *string `json:"netmask,omitempty" yaml:"netmask,omitempty"`
	Netmasklen       *int    `json:"netmasklen,omitempty" yaml:"netmasklen,omitempty"`
	NetworkAddress   *string `json:"networkAddress,omitempty" yaml:"networkAddress,omitempty"`
	StartAddress     *string `json:"startAddress,omitempty" yaml:"startAddress,omitempty"`
	VirtualNetworkId *string `json:"virtualNetworkId,omitempty" yaml:"virtualNetworkId,omitempty"`
}

// Image defines model for Image.
type Image struct {
	ApiVersion string    `json:"apiVersion" yaml:"apiVersion"`
	Kind       string    `json:"kind" yaml:"kind"`
	Metadata   Metadata  `json:"metadata" yaml:"metadata"`
	Spec       ImageSpec `json:"spec" yaml:"spec"`
	Status     *Status   `json:"status,omitempty" yaml:"status,omitempty"`
}

// ImageSpec defines model for ImageSpec.
type ImageSpec struct {
	Kind          *string `json:"kind,omitempty" yaml:"kind,omitempty"`
	LogicalVolume *string `json:"logicalVolume,omitempty" yaml:"logicalVolume,omitempty"`
	LvPath        *string `json:"lvPath,omitempty" yaml:"lvPath,omitempty"`
	OsName        *string `json:"osName,omitempty" yaml:"osName,omitempty"`
	OsVersion     *string `json:"osVersion,omitempty" yaml:"osVersion,omitempty"`
	Qcow2Path     *string `json:"qcow2Path,omitempty" yaml:"qcow2Path,omitempty"`
	Size          *int    `json:"size,omitempty" yaml:"size,omitempty"`
	SourceUrl     *string `json:"sourceUrl,omitempty" yaml:"sourceUrl,omitempty"`
	Type          *string `json:"type,omitempty" yaml:"type,omitempty"`
	VolumeGroup   *string `json:"volumeGroup,omitempty" yaml:"volumeGroup,omitempty"`
}

// Job defines model for Job.
type Job struct {
	Id       string    `json:"id" yaml:"id"`
	Metadata *Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     *JobSpec  `json:"spec,omitempty" yaml:"spec,omitempty"`
	Status   *Status   `json:"status,omitempty" yaml:"status,omitempty"`
}

// JobSpec defines model for JobSpec.
type JobSpec struct {
	Command     *[]string  `json:"command,omitempty" yaml:"command,omitempty"`
	ExitCode    *int       `json:"exitCode,omitempty" yaml:"exitCode,omitempty"`
	FinishTime  *time.Time `json:"finishTime,omitempty" yaml:"finishTime,omitempty"`
	MaxTime     *time.Time `json:"maxTime,omitempty" yaml:"maxTime,omitempty"`
	RequestTime *time.Time `json:"requestTime,omitempty" yaml:"requestTime,omitempty"`
	StartTime   *time.Time `json:"startTime,omitempty" yaml:"startTime,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Comment      *string                 `json:"comment,omitempty" yaml:"comment,omitempty"`
	Id           string                  `json:"id" yaml:"id"`
	InstanceName *string                 `json:"instanceName,omitempty" yaml:"instanceName,omitempty"`
	Key          *string                 `json:"key,omitempty" yaml:"key,omitempty"`
	Labels       *map[string]interface{} `json:"labels,omitempty" yaml:"labels,omitempty"`
	Name         string                  `json:"name" yaml:"name"`
	NodeName     *string                 `json:"nodeName,omitempty" yaml:"nodeName,omitempty"`
	Uuid         *string                 `json:"uuid,omitempty" yaml:"uuid,omitempty"`
}

// Nameservers defines model for Nameservers.
type Nameservers struct {
	Addresses *[]string `json:"addresses,omitempty" yaml:"addresses,omitempty"`
	Search    *[]string `json:"search,omitempty" yaml:"search,omitempty"`
}

// NetworkInterface defines model for NetworkInterface.
type NetworkInterface struct {
	Address     *string      `json:"address,omitempty" yaml:"address,omitempty"`
	Dhcp4       *bool        `json:"dhcp4,omitempty" yaml:"dhcp4,omitempty"`
	Dhcp6       *bool        `json:"dhcp6,omitempty" yaml:"dhcp6,omitempty"`
	Ethernet    *string      `json:"ethernet,omitempty" yaml:"ethernet,omitempty"`
	IpGateway   *string      `json:"ipGateway,omitempty" yaml:"ipGateway,omitempty"`
	IpNetworkId *string      `json:"ipNetworkId,omitempty" yaml:"ipNetworkId,omitempty"`
	Mac         *string      `json:"mac,omitempty" yaml:"mac,omitempty"`
	Nameservers *Nameservers `json:"nameservers,omitempty" yaml:"nameservers,omitempty"`
	Netmask     *string      `json:"netmask,omitempty" yaml:"netmask,omitempty"`
	Netmasklen  *int         `json:"netmasklen,omitempty" yaml:"netmasklen,omitempty"`
	Networkid   string       `json:"networkid" yaml:"networkid"`
	Networkname string       `json:"networkname" yaml:"networkname"`
	Portgroup   *string      `json:"portgroup,omitempty" yaml:"portgroup,omitempty"`
	Routes      *[]Route     `json:"routes,omitempty" yaml:"routes,omitempty"`
	Uuid        *string      `json:"uuid,omitempty" yaml:"uuid,omitempty"`
	Vlans       *[]uint      `json:"vlans,omitempty" yaml:"vlans,omitempty"`
}

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping" yaml:"ping"`
}

// ReplyMessage defines model for ReplyMessage.
type ReplyMessage struct {
	Message string `json:"message" yaml:"message"`
}

// Route defines model for Route.
type Route struct {
	To  *string `json:"to,omitempty" yaml:"to,omitempty"`
	Via *string `json:"via,omitempty" yaml:"via,omitempty"`
}

// Server defines model for Server.
type Server struct {
	ApiVersion string     `json:"apiVersion" yaml:"apiVersion"`
	Kind       string     `json:"kind" yaml:"kind"`
	Metadata   Metadata   `json:"metadata" yaml:"metadata"`
	Spec       ServerSpec `json:"spec" yaml:"spec"`
	Status     *Status    `json:"status,omitempty" yaml:"status,omitempty"`
}

// ServerSpec defines model for ServerSpec.
type ServerSpec struct {
	Auth             *Auth               `json:"auth,omitempty" yaml:"auth,omitempty"`
	BootVolume       *Volume             `json:"bootVolume,omitempty" yaml:"bootVolume,omitempty"`
	Cpu              *int                `json:"cpu,omitempty" yaml:"cpu,omitempty"`
	Memory           *int                `json:"memory,omitempty" yaml:"memory,omitempty"`
	NetworkInterface *[]NetworkInterface `json:"networkInterface,omitempty" yaml:"networkInterface,omitempty"`
	OsLv             *string             `json:"osLv,omitempty" yaml:"osLv,omitempty"`
	OsVariant        *string             `json:"osVariant,omitempty" yaml:"osVariant,omitempty"`
	OsVg             *string             `json:"osVg,omitempty" yaml:"osVg,omitempty"`
	Storage          *[]Volume           `json:"storage,omitempty" yaml:"storage,omitempty"`
}

// Servers defines model for Servers.
type Servers = []Server

// Status defines model for Status.
type Status struct {
	Console             *string    `json:"console,omitempty" yaml:"console,omitempty"`
	CreationTimeStamp   *time.Time `json:"creationTimeStamp,omitempty" yaml:"creationTimeStamp,omitempty"`
	DeletionTimeStamp   *time.Time `json:"deletionTimeStamp,omitempty" yaml:"deletionTimeStamp,omitempty"`
	LastUpdateTimeStamp *time.Time `json:"lastUpdateTimeStamp,omitempty" yaml:"lastUpdateTimeStamp,omitempty"`
	Message             *string    `json:"message,omitempty" yaml:"message,omitempty"`
	Status              *string    `json:"status,omitempty" yaml:"status,omitempty"`
	StatusCode          int        `json:"statusCode" yaml:"statusCode"`
}

// Success defines model for Success.
type Success struct {
	Id      string  `json:"id" yaml:"id"`
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

// Version defines model for Version.
type Version struct {
	ClientVersion string  `json:"clientVersion" yaml:"clientVersion"`
	ServerVersion *string `json:"serverVersion,omitempty" yaml:"serverVersion,omitempty"`
}

// VirtualNetwork defines model for VirtualNetwork.
type VirtualNetwork struct {
	ApiVersion string             `json:"apiVersion" yaml:"apiVersion"`
	Kind       string             `json:"kind" yaml:"kind"`
	Metadata   Metadata           `json:"metadata" yaml:"metadata"`
	Spec       VirtualNetworkSpec `json:"spec" yaml:"spec"`
	Status     *Status            `json:"status,omitempty" yaml:"status,omitempty"`
}

// VirtualNetworkSpec defines model for VirtualNetworkSpec.
type VirtualNetworkSpec struct {
	BridgeName       *string `json:"bridgeName,omitempty" yaml:"bridgeName,omitempty"`
	Dhcp             *bool   `json:"dhcp,omitempty" yaml:"dhcp,omitempty"`
	DhcpEndAddress   *string `json:"dhcpEndAddress,omitempty" yaml:"dhcpEndAddress,omitempty"`
	DhcpStartAddress *string `json:"dhcpStartAddress,omitempty" yaml:"dhcpStartAddress,omitempty"`
	ForwardMode      *string `json:"forwardMode,omitempty" yaml:"forwardMode,omitempty"`
	IPNetworkAddress *string `json:"iPNetworkAddress,omitempty" yaml:"iPNetworkAddress,omitempty"`
	IpAddress        *string `json:"ipAddress,omitempty" yaml:"ipAddress,omitempty"`
	IpNetworkId      *string `json:"ipNetworkId,omitempty" yaml:"ipNetworkId,omitempty"`
	MacAddress       *string `json:"macAddress,omitempty" yaml:"macAddress,omitempty"`
	Nat              *bool   `json:"nat,omitempty" yaml:"nat,omitempty"`
	Netmask          *string `json:"netmask,omitempty" yaml:"netmask,omitempty"`

	// OverlayMode Overlay mode for multi-node networks: 'none' (default), 'geneve' (OVN-managed), or 'vxlan' (deprecated).
	OverlayMode *VirtualNetworkSpecOverlayMode `json:"overlayMode,omitempty" yaml:"overlayMode,omitempty"`

	// PeerPolicy Policy for peer management: 'auto' or 'manual'. This field is ignored when OVN manages peers.
	PeerPolicy *VirtualNetworkSpecPeerPolicy `json:"peerPolicy,omitempty" yaml:"peerPolicy,omitempty"`
	Stp        *bool                         `json:"stp,omitempty" yaml:"stp,omitempty"`

	// UnderlayInterface Interface name for underlay network used by overlay tunnels.
	UnderlayInterface *string `json:"underlayInterface,omitempty" yaml:"underlayInterface,omitempty"`

	// Vni Overlay VNI (0-16777215) used by Geneve/VXLAN.
	Vni *int `json:"vni,omitempty" yaml:"vni,omitempty"`

	// VpnAccess Enable VPN route injection for servers on this network.
	VpnAccess *bool `json:"vpnAccess,omitempty" yaml:"vpnAccess,omitempty"`
}

// VirtualNetworkSpecOverlayMode Overlay mode for multi-node networks: 'none' (default), 'geneve' (OVN-managed), or 'vxlan' (deprecated).
type VirtualNetworkSpecOverlayMode string

// VirtualNetworkSpecPeerPolicy Policy for peer management: 'auto' or 'manual'. This field is ignored when OVN manages peers.
type VirtualNetworkSpecPeerPolicy string

// VolSpec defines model for VolSpec.
type VolSpec struct {
	Iscsi          *bool   `json:"iscsi,omitempty" yaml:"iscsi,omitempty"`
	IscsiTargetIqn *string `json:"iscsiTargetIqn,omitempty" yaml:"iscsiTargetIqn,omitempty"`
	Kind           *string `json:"kind,omitempty" yaml:"kind,omitempty"`
	LogicalVolume  *string `json:"logicalVolume,omitempty" yaml:"logicalVolume,omitempty"`
	OsVariant      *string `json:"osVariant,omitempty" yaml:"osVariant,omitempty"`
	Path           *string `json:"path,omitempty" yaml:"path,omitempty"`
	Persistent     *bool   `json:"persistent,omitempty" yaml:"persistent,omitempty"`
	Size           *int    `json:"size,omitempty" yaml:"size,omitempty"`
	Type           *string `json:"type,omitempty" yaml:"type,omitempty"`
	VolumeGroup    *string `json:"volumeGroup,omitempty" yaml:"volumeGroup,omitempty"`
}

// Volume defines model for Volume.
type Volume struct {
	ApiVersion string   `json:"apiVersion" yaml:"apiVersion"`
	Kind       string   `json:"kind" yaml:"kind"`
	Metadata   Metadata `json:"metadata" yaml:"metadata"`
	Spec       VolSpec  `json:"spec" yaml:"spec"`
	Status     *Status  `json:"status,omitempty" yaml:"status,omitempty"`
}

// VpnGateway defines model for VpnGateway.
type VpnGateway struct {
	ApiVersion string         `json:"apiVersion" yaml:"apiVersion"`
	Kind       string         `json:"kind" yaml:"kind"`
	Metadata   Metadata       `json:"metadata" yaml:"metadata"`
	Spec       VpnGatewaySpec `json:"spec" yaml:"spec"`
	Status     *Status        `json:"status,omitempty" yaml:"status,omitempty"`
}

// VpnGatewaySpec defines model for VpnGatewaySpec.
type VpnGatewaySpec struct {
	BindPublicIpAddress    string `json:"bindPublicIpAddress" yaml:"bindPublicIpAddress"`
	InternalVirtualNetwork string `json:"internalVirtualNetwork" yaml:"internalVirtualNetwork"`

	// RemoteCIDRs Source CIDR list allowed to access vpn gateway. Empty means allow all.
	RemoteCIDRs []string `json:"remoteCIDRs,omitempty" yaml:"remoteCIDRs,omitempty"`
}

// ApiCreateLoadBalancerJSONRequestBody defines body for ApiCreateLoadBalancer for application/json ContentType.
type ApiCreateLoadBalancerJSONRequestBody = ApplicationLoadBalancer

// ApiUpdateLoadBalancerByIdJSONRequestBody defines body for ApiUpdateLoadBalancerById for application/json ContentType.
type ApiUpdateLoadBalancerByIdJSONRequestBody = ApplicationLoadBalancer

// ApiCreateGatewayJSONRequestBody defines body for ApiCreateGateway for application/json ContentType.
type ApiCreateGatewayJSONRequestBody = Gateway

// ApiUpdateGatewayByIdJSONRequestBody defines body for ApiUpdateGatewayById for application/json ContentType.
type ApiUpdateGatewayByIdJSONRequestBody = Gateway

// ApiCreateImageJSONRequestBody defines body for ApiCreateImage for application/json ContentType.
type ApiCreateImageJSONRequestBody = Image

// ApiUpdateImageByIdJSONRequestBody defines body for ApiUpdateImageById for application/json ContentType.
type ApiUpdateImageByIdJSONRequestBody = Image

// ApiCreateNetworkJSONRequestBody defines body for ApiCreateNetwork for application/json ContentType.
type ApiCreateNetworkJSONRequestBody = VirtualNetwork

// ApiUpdateNetworkByIdJSONRequestBody defines body for ApiUpdateNetworkById for application/json ContentType.
type ApiUpdateNetworkByIdJSONRequestBody = VirtualNetwork

// ApiCreateServerJSONRequestBody defines body for ApiCreateServer for application/json ContentType.
type ApiCreateServerJSONRequestBody = Server

// ApiMakeImageEntryFromRunningVMByIdJSONRequestBody defines body for ApiMakeImageEntryFromRunningVMById for application/json ContentType.
type ApiMakeImageEntryFromRunningVMByIdJSONRequestBody = Image

// ApiUpdateServerByIdJSONRequestBody defines body for ApiUpdateServerById for application/json ContentType.
type ApiUpdateServerByIdJSONRequestBody = Server

// ApiCreateVolumeJSONRequestBody defines body for ApiCreateVolume for application/json ContentType.
type ApiCreateVolumeJSONRequestBody = Volume

// ApiUpdateVolumeByIdJSONRequestBody defines body for ApiUpdateVolumeById for application/json ContentType.
type ApiUpdateVolumeByIdJSONRequestBody = Volume

// ApiCreateVpnGatewayJSONRequestBody defines body for ApiCreateVpnGateway for application/json ContentType.
type ApiCreateVpnGatewayJSONRequestBody = VpnGateway

// ApiUpdateVpnGatewayByIdJSONRequestBody defines body for ApiUpdateVpnGatewayById for application/json ContentType.
type ApiUpdateVpnGatewayByIdJSONRequestBody = VpnGateway

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List LoadBalancers
	// (GET /application-load-balancer)
	ApiGetLoadBalancers(ctx echo.Context) error
	// Create LoadBalancer
	// (POST /application-load-balancer)
	ApiCreateLoadBalancer(ctx echo.Context) error
	// Delete LoadBalancer
	// (DELETE /application-load-balancer/{id})
	ApiDeleteLoadBalancerById(ctx echo.Context, id string) error
	// Info for a specific LoadBalancer
	// (GET /application-load-balancer/{id})
	ApiGetLoadBalancerById(ctx echo.Context, id string) error
	// Update LoadBalancer
	// (PUT /application-load-balancer/{id})
	ApiUpdateLoadBalancerById(ctx echo.Context, id string) error
	// List Gateways
	// (GET /gateway)
	ApiGetGateways(ctx echo.Context) error
	// Create Gateway
	// (POST /gateway)
	ApiCreateGateway(ctx echo.Context) error
	// Delete Gateway
	// (DELETE /gateway/{id})
	ApiDeleteGatewayById(ctx echo.Context, id string) error
	// Info for a specific gateway
	// (GET /gateway/{id})
	ApiGetGatewayById(ctx echo.Context, id string) error
	// Update Gateway
	// (PUT /gateway/{id})
	ApiUpdateGatewayById(ctx echo.Context, id string) error
	// Download VPN cert profile for gateway
	// (GET /gateway/{id}/cert)
	ApiGetGatewayCertById(ctx echo.Context, id string) error
	// List Images
	// (GET /image)
	ApiGetImages(ctx echo.Context) error
	// Create Image
	// (POST /image)
	ApiCreateImage(ctx echo.Context) error
	// Delete Image
	// (DELETE /image/{id})
	ApiDeleteImageById(ctx echo.Context, id string) error
	// Info for a specific image
	// (GET /image/{id})
	ApiGetImageById(ctx echo.Context, id string) error
	// Update Image
	// (PUT /image/{id})
	ApiUpdateImageById(ctx echo.Context, id string) error
	// List all assigned IP Networks
	// (GET /ipnetwork)
	ApiListIpNetworks(ctx echo.Context) error
	// Get assigned IP addresses for a specific IP network
	// (GET /ipnetwork/{id}/addresses)
	ApiGetIpAddressesByNetwork(ctx echo.Context, id string) error
	// Get Marmot Cluster Status
	// (GET /marmot/cluster)
	ApiGetMarmotCluster(ctx echo.Context) error
	// Get Marmot Host Status
	// (GET /marmot/status)
	ApiGetMarmotStatus(ctx echo.Context) error
	// Get Network Information
	// (GET /network)
	ApiGetNetworks(ctx echo.Context) error
	// Create Virtual Network
	// (POST /network)
	ApiCreateNetwork(ctx echo.Context) error
	// Delete Virtual Network
	// (DELETE /network/{id})
	ApiDeleteNetworkById(ctx echo.Context, id string) error
	// Get particular virtual network Information
	// (GET /network/{id})
	ApiGetNetworkById(ctx echo.Context, id string) error
	// Update Virtual Network Information by Id
	// (PUT /network/{id})
	ApiUpdateNetworkById(ctx echo.Context, id string) error
	// Get IP networks for a virtual network
	// (GET /network/{id}/ipnetworks)
	ApiGetNetworkIpNetworks(ctx echo.Context, id string) error
	// Alive
	// (GET /ping)
	ApiReplyPing(ctx echo.Context) error
	// Get Server Information
	// (GET /server)
	ApiGetServers(ctx echo.Context) error
	// Create Virtual Server
	// (POST /server)
	ApiCreateServer(ctx echo.Context) error
	// Delete Server
	// (DELETE /server/{id})
	ApiDeleteServerById(ctx echo.Context, id string) error
	// Get particular server Information
	// (GET /server/{id})
	ApiGetServerById(ctx echo.Context, id string) error
	// Create image from Server Object by Id
	// (POST /server/{id})
	ApiMakeImageEntryFromRunningVMById(ctx echo.Context, id string) error
	// Update Server Information by Id
	// (PUT /server/{id})
	ApiUpdateServerById(ctx echo.Context, id string) error
	// Connect to Server Console by Id
	// (GET /server/{id}/console)
	ApiConsoleServerById(ctx echo.Context, id string) error
	// Start Server by Id
	// (POST /server/{id}/start)
	ApiStartServerById(ctx echo.Context, id string) error
	// Stop Server by Id
	// (POST /server/{id}/stop)
	ApiStopServerById(ctx echo.Context, id string) error
	// Get Version
	// (GET /version)
	ApiGetVersion(ctx echo.Context) error
	// List Volumes
	// (GET /volume)
	ApiListVolumes(ctx echo.Context) error
	// Create Volume
	// (POST /volume)
	ApiCreateVolume(ctx echo.Context) error
	// Delete Volume
	// (DELETE /volume/{volumeId})
	ApiDeleteVolumeById(ctx echo.Context, volumeId string) error
	// Info for a specific volume
	// (GET /volume/{volumeId})
	ApiShowVolumeById(ctx echo.Context, volumeId string) error
	// Update Volume
	// (PUT /volume/{volumeId})
	ApiUpdateVolumeById(ctx echo.Context, volumeId string) error
	// List VpnGateways
	// (GET /vpn-gateway)
	ApiGetVpnGateways(ctx echo.Context) error
	// Create VpnGateway
	// (POST /vpn-gateway)
	ApiCreateVpnGateway(ctx echo.Context) error
	// Delete VpnGateway
	// (DELETE /vpn-gateway/{id})
	ApiDeleteVpnGatewayById(ctx echo.Context, id string) error
	// Info for a specific VpnGateway
	// (GET /vpn-gateway/{id})
	ApiGetVpnGatewayById(ctx echo.Context, id string) error
	// Update VpnGateway
	// (PUT /vpn-gateway/{id})
	ApiUpdateVpnGatewayById(ctx echo.Context, id string) error
	// Download VPN cert profile for vpn gateway
	// (GET /vpn-gateway/{id}/cert)
	ApiGetVpnGatewayCertById(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ApiGetLoadBalancers converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetLoadBalancers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetLoadBalancers(ctx)
	return err
}

// ApiCreateLoadBalancer converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateLoadBalancer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateLoadBalancer(ctx)
	return err
}

// ApiDeleteLoadBalancerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteLoadBalancerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteLoadBalancerById(ctx, id)
	return err
}

// ApiGetLoadBalancerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetLoadBalancerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetLoadBalancerById(ctx, id)
	return err
}

// ApiUpdateLoadBalancerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateLoadBalancerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateLoadBalancerById(ctx, id)
	return err
}

// ApiGetGateways converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetGateways(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetGateways(ctx)
	return err
}

// ApiCreateGateway converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateGateway(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateGateway(ctx)
	return err
}

// ApiDeleteGatewayById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteGatewayById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteGatewayById(ctx, id)
	return err
}

// ApiGetGatewayById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetGatewayById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetGatewayById(ctx, id)
	return err
}

// ApiUpdateGatewayById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateGatewayById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateGatewayById(ctx, id)
	return err
}

// ApiGetGatewayCertById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetGatewayCertById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetGatewayCertById(ctx, id)
	return err
}

// ApiGetImages converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetImages(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetImages(ctx)
	return err
}

// ApiCreateImage converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateImage(ctx)
	return err
}

// ApiDeleteImageById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteImageById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteImageById(ctx, id)
	return err
}

// ApiGetImageById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetImageById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetImageById(ctx, id)
	return err
}

// ApiUpdateImageById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateImageById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateImageById(ctx, id)
	return err
}

// ApiListIpNetworks converts echo context to params.
func (w *ServerInterfaceWrapper) ApiListIpNetworks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiListIpNetworks(ctx)
	return err
}

// ApiGetIpAddressesByNetwork converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetIpAddressesByNetwork(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetIpAddressesByNetwork(ctx, id)
	return err
}

// ApiGetMarmotCluster converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetMarmotCluster(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetMarmotCluster(ctx)
	return err
}

// ApiGetMarmotStatus converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetMarmotStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetMarmotStatus(ctx)
	return err
}

// ApiGetNetworks converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetNetworks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetNetworks(ctx)
	return err
}

// ApiCreateNetwork converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateNetwork(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateNetwork(ctx)
	return err
}

// ApiDeleteNetworkById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteNetworkById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteNetworkById(ctx, id)
	return err
}

// ApiGetNetworkById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetNetworkById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetNetworkById(ctx, id)
	return err
}

// ApiUpdateNetworkById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateNetworkById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateNetworkById(ctx, id)
	return err
}

// ApiGetNetworkIpNetworks converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetNetworkIpNetworks(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetNetworkIpNetworks(ctx, id)
	return err
}

// ApiReplyPing converts echo context to params.
func (w *ServerInterfaceWrapper) ApiReplyPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiReplyPing(ctx)
	return err
}

// ApiGetServers converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetServers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetServers(ctx)
	return err
}

// ApiCreateServer converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateServer(ctx)
	return err
}

// ApiDeleteServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteServerById(ctx, id)
	return err
}

// ApiGetServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetServerById(ctx, id)
	return err
}

// ApiMakeImageEntryFromRunningVMById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiMakeImageEntryFromRunningVMById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiMakeImageEntryFromRunningVMById(ctx, id)
	return err
}

// ApiUpdateServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateServerById(ctx, id)
	return err
}

// ApiConsoleServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiConsoleServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiConsoleServerById(ctx, id)
	return err
}

// ApiStartServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiStartServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiStartServerById(ctx, id)
	return err
}

// ApiStopServerById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiStopServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiStopServerById(ctx, id)
	return err
}

// ApiGetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetVersion(ctx)
	return err
}

// ApiListVolumes converts echo context to params.
func (w *ServerInterfaceWrapper) ApiListVolumes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiListVolumes(ctx)
	return err
}

// ApiCreateVolume converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateVolume(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateVolume(ctx)
	return err
}

// ApiDeleteVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteVolumeById(ctx, volumeId)
	return err
}

// ApiShowVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiShowVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiShowVolumeById(ctx, volumeId)
	return err
}

// ApiUpdateVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateVolumeById(ctx, volumeId)
	return err
}

// ApiGetVpnGateways converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetVpnGateways(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetVpnGateways(ctx)
	return err
}

// ApiCreateVpnGateway converts echo context to params.
func (w *ServerInterfaceWrapper) ApiCreateVpnGateway(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiCreateVpnGateway(ctx)
	return err
}

// ApiDeleteVpnGatewayById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiDeleteVpnGatewayById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiDeleteVpnGatewayById(ctx, id)
	return err
}

// ApiGetVpnGatewayById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetVpnGatewayById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetVpnGatewayById(ctx, id)
	return err
}

// ApiUpdateVpnGatewayById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiUpdateVpnGatewayById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiUpdateVpnGatewayById(ctx, id)
	return err
}

// ApiGetVpnGatewayCertById converts echo context to params.
func (w *ServerInterfaceWrapper) ApiGetVpnGatewayCertById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiGetVpnGatewayCertById(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/application-load-balancer", wrapper.ApiGetLoadBalancers, options.OperationMiddlewares["apiGetLoadBalancers"]...)
	router.POST(options.BaseURL+"/application-load-balancer", wrapper.ApiCreateLoadBalancer, options.OperationMiddlewares["apiCreateLoadBalancer"]...)
	router.DELETE(options.BaseURL+"/application-load-balancer/:id", wrapper.ApiDeleteLoadBalancerById, options.OperationMiddlewares["apiDeleteLoadBalancerById"]...)
	router.GET(options.BaseURL+"/application-load-balancer/:id", wrapper.ApiGetLoadBalancerById, options.OperationMiddlewares["apiGetLoadBalancerById"]...)
	router.PUT(options.BaseURL+"/application-load-balancer/:id", wrapper.ApiUpdateLoadBalancerById, options.OperationMiddlewares["apiUpdateLoadBalancerById"]...)
	router.GET(options.BaseURL+"/gateway", wrapper.ApiGetGateways, options.OperationMiddlewares["apiGetGateways"]...)
	router.POST(options.BaseURL+"/gateway", wrapper.ApiCreateGateway, options.OperationMiddlewares["apiCreateGateway"]...)
	router.DELETE(options.BaseURL+"/gateway/:id", wrapper.ApiDeleteGatewayById, options.OperationMiddlewares["apiDeleteGatewayById"]...)
	router.GET(options.BaseURL+"/gateway/:id", wrapper.ApiGetGatewayById, options.OperationMiddlewares["apiGetGatewayById"]...)
	router.PUT(options.BaseURL+"/gateway/:id", wrapper.ApiUpdateGatewayById, options.OperationMiddlewares["apiUpdateGatewayById"]...)
	router.GET(options.BaseURL+"/gateway/:id/cert", wrapper.ApiGetGatewayCertById, options.OperationMiddlewares["apiGetGatewayCertById"]...)
	router.GET(options.BaseURL+"/image", wrapper.ApiGetImages, options.OperationMiddlewares["apiGetImages"]...)
	router.POST(options.BaseURL+"/image", wrapper.ApiCreateImage, options.OperationMiddlewares["apiCreateImage"]...)
	router.DELETE(options.BaseURL+"/image/:id", wrapper.ApiDeleteImageById, options.OperationMiddlewares["apiDeleteImageById"]...)
	router.GET(options.BaseURL+"/image/:id", wrapper.ApiGetImageById, options.OperationMiddlewares["apiGetImageById"]...)
	router.PUT(options.BaseURL+"/image/:id", wrapper.ApiUpdateImageById, options.OperationMiddlewares["apiUpdateImageById"]...)
	router.GET(options.BaseURL+"/ipnetwork", wrapper.ApiListIpNetworks, options.OperationMiddlewares["apiListIpNetworks"]...)
	router.GET(options.BaseURL+"/ipnetwork/:id/addresses", wrapper.ApiGetIpAddressesByNetwork, options.OperationMiddlewares["apiGetIpAddressesByNetwork"]...)
	router.GET(options.BaseURL+"/marmot/cluster", wrapper.ApiGetMarmotCluster, options.OperationMiddlewares["apiGetMarmotCluster"]...)
	router.GET(options.BaseURL+"/marmot/status", wrapper.ApiGetMarmotStatus, options.OperationMiddlewares["apiGetMarmotStatus"]...)
	router.GET(options.BaseURL+"/network", wrapper.ApiGetNetworks, options.OperationMiddlewares["apiGetNetworks"]...)
	router.POST(options.BaseURL+"/network", wrapper.ApiCreateNetwork, options.OperationMiddlewares["apiCreateNetwork"]...)
	router.DELETE(options.BaseURL+"/network/:id", wrapper.ApiDeleteNetworkById, options.OperationMiddlewares["apiDeleteNetworkById"]...)
	router.GET(options.BaseURL+"/network/:id", wrapper.ApiGetNetworkById, options.OperationMiddlewares["apiGetNetworkById"]...)
	router.PUT(options.BaseURL+"/network/:id", wrapper.ApiUpdateNetworkById, options.OperationMiddlewares["apiUpdateNetworkById"]...)
	router.GET(options.BaseURL+"/network/:id/ipnetworks", wrapper.ApiGetNetworkIpNetworks, options.OperationMiddlewares["apiGetNetworkIpNetworks"]...)
	router.GET(options.BaseURL+"/ping", wrapper.ApiReplyPing, options.OperationMiddlewares["apiReplyPing"]...)
	router.GET(options.BaseURL+"/server", wrapper.ApiGetServers, options.OperationMiddlewares["apiGetServers"]...)
	router.POST(options.BaseURL+"/server", wrapper.ApiCreateServer, options.OperationMiddlewares["apiCreateServer"]...)
	router.DELETE(options.BaseURL+"/server/:id", wrapper.ApiDeleteServerById, options.OperationMiddlewares["apiDeleteServerById"]...)
	router.GET(options.BaseURL+"/server/:id", wrapper.ApiGetServerById, options.OperationMiddlewares["apiGetServerById"]...)
	router.POST(options.BaseURL+"/server/:id", wrapper.ApiMakeImageEntryFromRunningVMById, options.OperationMiddlewares["apiMakeImageEntryFromRunningVMById"]...)
	router.PUT(options.BaseURL+"/server/:id", wrapper.ApiUpdateServerById, options.OperationMiddlewares["apiUpdateServerById"]...)
	router.GET(options.BaseURL+"/server/:id/console", wrapper.ApiConsoleServerById, options.OperationMiddlewares["apiConsoleServerById"]...)
	router.POST(options.BaseURL+"/server/:id/start", wrapper.ApiStartServerById, options.OperationMiddlewares["apiStartServerById"]...)
	router.POST(options.BaseURL+"/server/:id/stop", wrapper.ApiStopServerById, options.OperationMiddlewares["apiStopServerById"]...)
	router.GET(options.BaseURL+"/version", wrapper.ApiGetVersion, options.OperationMiddlewares["apiGetVersion"]...)
	router.GET(options.BaseURL+"/volume", wrapper.ApiListVolumes, options.OperationMiddlewares["apiListVolumes"]...)
	router.POST(options.BaseURL+"/volume", wrapper.ApiCreateVolume, options.OperationMiddlewares["apiCreateVolume"]...)
	router.DELETE(options.BaseURL+"/volume/:volumeId", wrapper.ApiDeleteVolumeById, options.OperationMiddlewares["apiDeleteVolumeById"]...)
	router.GET(options.BaseURL+"/volume/:volumeId", wrapper.ApiShowVolumeById, options.OperationMiddlewares["apiShowVolumeById"]...)
	router.PUT(options.BaseURL+"/volume/:volumeId", wrapper.ApiUpdateVolumeById, options.OperationMiddlewares["apiUpdateVolumeById"]...)
	router.GET(options.BaseURL+"/vpn-gateway", wrapper.ApiGetVpnGateways, options.OperationMiddlewares["apiGetVpnGateways"]...)
	router.POST(options.BaseURL+"/vpn-gateway", wrapper.ApiCreateVpnGateway, options.OperationMiddlewares["apiCreateVpnGateway"]...)
	router.DELETE(options.BaseURL+"/vpn-gateway/:id", wrapper.ApiDeleteVpnGatewayById, options.OperationMiddlewares["apiDeleteVpnGatewayById"]...)
	router.GET(options.BaseURL+"/vpn-gateway/:id", wrapper.ApiGetVpnGatewayById, options.OperationMiddlewares["apiGetVpnGatewayById"]...)
	router.PUT(options.BaseURL+"/vpn-gateway/:id", wrapper.ApiUpdateVpnGatewayById, options.OperationMiddlewares["apiUpdateVpnGatewayById"]...)
	router.GET(options.BaseURL+"/vpn-gateway/:id/cert", wrapper.ApiGetVpnGatewayCertById, options.OperationMiddlewares["apiGetVpnGatewayCertById"]...)

}
