// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Comment      *string `json:"comment,omitempty"`
	Id           *string `json:"id,omitempty"`
	InstanceName *string `json:"instanceName,omitempty"`
	Key          *string `json:"key,omitempty"`
	Name         *string `json:"name,omitempty"`
	Uuid         *string `json:"uuid,omitempty"`
}

// Nameservers defines model for Nameservers.
type Nameservers struct {
	Addresses *[]string `json:"addresses,omitempty"`
	Search    *[]string `json:"search,omitempty"`
}

// Network defines model for Network.
type Network struct {
	Address     *string      `json:"address,omitempty"`
	Dhcp4       *bool        `json:"dhcp4,omitempty"`
	Dhcp6       *bool        `json:"dhcp6,omitempty"`
	Ethernet    *string      `json:"ethernet,omitempty"`
	Id          string       `json:"id"`
	Mac         *string      `json:"mac,omitempty"`
	Nameservers *Nameservers `json:"nameservers,omitempty"`
	Netmask     *string      `json:"netmask,omitempty"`
	Networkname *string      `json:"networkname,omitempty"`
	Portgroup   *string      `json:"portgroup,omitempty"`
	Routes      *[]Route     `json:"routes,omitempty"`
	Uuid        *string      `json:"uuid,omitempty"`
	Vlans       *[]uint      `json:"vlans,omitempty"`
}

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}

// ReplyMessage defines model for ReplyMessage.
type ReplyMessage struct {
	Message string `json:"message"`
}

// Route defines model for Route.
type Route struct {
	To  *string `json:"to,omitempty"`
	Via *string `json:"via,omitempty"`
}

// Server defines model for Server.
type Server struct {
	Metadata *Metadata `json:"Metadata,omitempty"`
	Spec     *VmSpec   `json:"Spec,omitempty"`
	Status2  *Status   `json:"Status2,omitempty"`
	Id       string    `json:"id"`
}

// Servers defines model for Servers.
type Servers = []Server

// Status defines model for Status.
type Status struct {
	CreationTimeStamp   *time.Time `json:"creationTimeStamp,omitempty"`
	DeletionTimeStamp   *time.Time `json:"deletionTimeStamp,omitempty"`
	LastUpdateTimeStamp *time.Time `json:"lastUpdateTimeStamp,omitempty"`
	Message             *string    `json:"message,omitempty"`
	Status              *int       `json:"status,omitempty"`
}

// Success defines model for Success.
type Success struct {
	Id      string  `json:"id"`
	Message *string `json:"message,omitempty"`
}

// Version defines model for Version.
type Version struct {
	ClientVersion string  `json:"clientVersion"`
	ServerVersion *string `json:"serverVersion,omitempty"`
}

// VmSpec defines model for VmSpec.
type VmSpec struct {
	Network    *[]Network `json:"Network,omitempty"`
	Storage    *[]Volume  `json:"Storage,omitempty"`
	BootVolume *Volume    `json:"bootVolume,omitempty"`
	Cpu        *int       `json:"cpu,omitempty"`
	Memory     *int       `json:"memory,omitempty"`
	OsLv       *string    `json:"osLv,omitempty"`
	OsVariant  *string    `json:"osVariant,omitempty"`
	OsVg       *string    `json:"osVg,omitempty"`
}

// Volume defines model for Volume.
type Volume struct {
	CTime         *time.Time `json:"cTime,omitempty"`
	Comment       *string    `json:"comment,omitempty"`
	Id            string     `json:"id"`
	Key           *string    `json:"key,omitempty"`
	Kind          *string    `json:"kind,omitempty"`
	LogicalVolume *string    `json:"logicalVolume,omitempty"`
	MTime         *time.Time `json:"mTime,omitempty"`
	Name          *string    `json:"name,omitempty"`
	OsVariant     *string    `json:"osVariant,omitempty"`
	Path          *string    `json:"path,omitempty"`
	Persistent    *bool      `json:"persistent,omitempty"`
	Size          *int       `json:"size,omitempty"`
	Status        *int       `json:"status,omitempty"`
	Type          *string    `json:"type,omitempty"`
	VolumeGroup   *string    `json:"volumeGroup,omitempty"`
}

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = Server

// UpdateServerByIdJSONRequestBody defines body for UpdateServerById for application/json ContentType.
type UpdateServerByIdJSONRequestBody = Server

// CreateVolumeJSONRequestBody defines body for CreateVolume for application/json ContentType.
type CreateVolumeJSONRequestBody = Volume

// UpdateVolumeByIdJSONRequestBody defines body for UpdateVolumeById for application/json ContentType.
type UpdateVolumeByIdJSONRequestBody = Volume

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Alive
	// (GET /ping)
	ReplyPing(ctx echo.Context) error
	// Get Server Information
	// (GET /server)
	GetServers(ctx echo.Context) error
	// Create Virtual Server
	// (POST /server)
	CreateServer(ctx echo.Context) error
	// Delete Server
	// (DELETE /server/{id})
	DeleteServerById(ctx echo.Context, id string) error
	// Get particular server Information
	// (GET /server/{id})
	GetServerById(ctx echo.Context, id string) error
	// Update Server Information by Id
	// (PUT /server/{id})
	UpdateServerById(ctx echo.Context, id string) error
	// Get Version
	// (GET /version)
	GetVersion(ctx echo.Context) error
	// List Volumes
	// (GET /volume)
	ListVolumes(ctx echo.Context) error
	// Create Volume
	// (POST /volume)
	CreateVolume(ctx echo.Context) error
	// Delete Volume
	// (DELETE /volume/{volumeId})
	DeleteVolumeById(ctx echo.Context, volumeId string) error
	// Info for a specific volume
	// (GET /volume/{volumeId})
	ShowVolumeById(ctx echo.Context, volumeId string) error
	// Update Volume
	// (PUT /volume/{volumeId})
	UpdateVolumeById(ctx echo.Context, volumeId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ReplyPing converts echo context to params.
func (w *ServerInterfaceWrapper) ReplyPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReplyPing(ctx)
	return err
}

// GetServers converts echo context to params.
func (w *ServerInterfaceWrapper) GetServers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServers(ctx)
	return err
}

// CreateServer converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateServer(ctx)
	return err
}

// DeleteServerById converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteServerById(ctx, id)
	return err
}

// GetServerById converts echo context to params.
func (w *ServerInterfaceWrapper) GetServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServerById(ctx, id)
	return err
}

// UpdateServerById converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateServerById(ctx, id)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// ListVolumes converts echo context to params.
func (w *ServerInterfaceWrapper) ListVolumes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListVolumes(ctx)
	return err
}

// CreateVolume converts echo context to params.
func (w *ServerInterfaceWrapper) CreateVolume(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateVolume(ctx)
	return err
}

// DeleteVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteVolumeById(ctx, volumeId)
	return err
}

// ShowVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) ShowVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ShowVolumeById(ctx, volumeId)
	return err
}

// UpdateVolumeById converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateVolumeById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", ctx.Param("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter volumeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateVolumeById(ctx, volumeId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/ping", wrapper.ReplyPing)
	router.GET(baseURL+"/server", wrapper.GetServers)
	router.POST(baseURL+"/server", wrapper.CreateServer)
	router.DELETE(baseURL+"/server/:id", wrapper.DeleteServerById)
	router.GET(baseURL+"/server/:id", wrapper.GetServerById)
	router.PUT(baseURL+"/server/:id", wrapper.UpdateServerById)
	router.GET(baseURL+"/version", wrapper.GetVersion)
	router.GET(baseURL+"/volume", wrapper.ListVolumes)
	router.POST(baseURL+"/volume", wrapper.CreateVolume)
	router.DELETE(baseURL+"/volume/:volumeId", wrapper.DeleteVolumeById)
	router.GET(baseURL+"/volume/:volumeId", wrapper.ShowVolumeById)
	router.PUT(baseURL+"/volume/:volumeId", wrapper.UpdateVolumeById)

}
