openapi: "3.0.3"
info:
  version: 0.1.0
  title: REST API of Marmot Server
servers:
  - url: http://0.0.0.0:{port}{basePath}
    description: Marmot Server API
    variables:
      port:
        enum:
          - "8080"
        default: "8080"
      basePath:
        default: /api/v1
        description: Base path for the API
tags:
  - name: user
  - name: version
paths:
  /version:
    get:
      summary: "Get Version"
      operationId: getVersion
      tags:
        - version
      responses:
        "200":
          description: Get Marmot Server Version
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
  /ping:
    get:
      summary: "Alive"
      operationId: replyPing
      tags:
        - alive
      responses:
        "200":
          description: Check Marmot Server is Alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReplyMessage"
  /volume:
    post:
      summary: "Create Volume"
      operationId: createVolume
      tags:
        - storage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Volume"
      responses:
        "200":
          description: Created the Volume
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "List Volumes"
      operationId: listVolumes
      tags:
        - storage
      responses:
        "200":
          description: List of Volumes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Volume"
  /volume/{volumeId}:
    get:
      summary: "Info for a specific volume"
      operationId: showVolumeById
      tags:
        - storage
      parameters:
        - name: volumeId
          in: path
          required: true
          description: The id of the volume to retrieve
          schema:
            type: string
    put:
      summary: "Update Volume"
      operationId: updateVolumeById
      tags:
        - storage
      parameters:
        - name: volumeId
          in: path
          required: true
          description: The id of the volume to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Volume"
      responses:
        "200":
          description: Updated the Volume
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete Volume"
      operationId: deleteVolumeById
      tags:
        - storage
      parameters:
        - name: volumeId
          in: path
          required: true
          description: The id of the volume to delete
          schema:
            type: string
      responses:
        "200":
          description: Deleted the Volume
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /server:
    post:
      summary: "Create Virtual Server"
      description: |
        Create a new virtual server. The virtual server specifications are specified in the request body.
        If the virtual server is successfully created, the information of the created virtual server is returned in the response.
        The virtual server is then automatically started.
        The virtual server specifications include CPU, memory, storage, network settings, and more.
        If an error occurs during virtual server creation, an appropriate error message is returned.
      operationId: createServer
      tags:
        - server
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Server"
      responses:
        "201":
          description: "Successfully created and started the virtual server."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        default:
          description: "An error occurred."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "Get Server Information"
      description: |
        Retrieve information about existing virtual servers. A list of virtual servers is returned in the response.
        Each virtual server's information includes server ID, status, resource usage, and more.
        If no virtual servers exist or an error occurs while retrieving information, an appropriate error message is returned.
      operationId: getServers
      tags:
        - server
      responses:
        "200":
          description: "Successfully retrieved the list of servers."
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Servers"
        default:
          description: "An error occurred."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /server/{id}:
      get:
        summary: "Get particular server Information"
        operationId: getServerById
        tags:
          - server
        parameters:
          - name: id
            in: path
            required: true
            description: The ID identifies the server.
            schema:
              type: string
        responses:
          "200":
            description: "Successfully retrieved the server information."
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Server"
          default:
            description: "An error occurred."
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
      put:
        summary: "Update Server Information by Id"
        operationId: updateServerById
        tags:
          - server
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the server to update
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Server"
        responses:
          "200":
            description: Updated the Server
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
      delete:
        summary: "Delete Server"
        operationId: deleteServerById
        tags:
          - server
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the server to delete
            schema:
              type: string
        responses:
          "200":
            description: Deleted the Server
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /network:
    post:
      summary: "Create Virtual Network"
      description: |
        Create a new virtual network. The virtual network specifications are specified in the request body.
        If the virtual network is successfully created, the information of the created virtual network is returned in the response.
        The virtual network specifications include network name, IP address range, DHCP settings, and more.
        If an error occurs during virtual network creation, an appropriate error message is returned.
      operationId: createNetwork
      tags:
        - network
        - virtual-network
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VirtualNetwork"
      responses:
        "201":
          description: "Successfully created the virtual network."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        default:
          description: "An error occurred."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "Get Network Information"
      description: |
        Retrieve information about existing virtual networks. A list of virtual networks is returned in the response.
        Each virtual network's information includes network ID, status, IP address range, DHCP settings, and more.
        If no virtual networks exist or an error occurs while retrieving information, an appropriate error message is returned.
      operationId: getNetworks
      tags:
        - network
      responses:
        "200":
          description: "Successfully retrieved the list of networks."
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/VirtualNetwork"
        default:
          description: "An error occurred."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error" 
  /network/{id}:
      get:
        summary: "Get particular virtual network Information"
        operationId: getNetworkById
        tags:
          - network
          - virtual-network
        parameters:
          - name: id
            in: path
            required: true
            description: The ID identifies the virtual network.
            schema:
              type: string
        responses:
          "200":
            description: "Successfully retrieved the virtual network information."
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/VirtualNetwork"
          default:
            description: "An error occurred."
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
      put:
        summary: "Update Virtual Network Information by Id"
        operationId: updateNetworkById
        tags:
          - network
          - virtual-network
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the virtual network to update
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetwork"
        responses:
          "200":
            description: Updated the Virtual Network
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
      delete:
        summary: "Delete Virtual Network"
        operationId: deleteNetworkById
        tags:
          - network
          - virtual-network
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the virtual network to delete
            schema:
              type: string
        responses:
          "200":
            description: Deleted the Virtual Network
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"

components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    Version:
      type: object
      required:
        - clientVersion
      properties:
        serverVersion:
          type: string
        clientVersion:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Success:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        message:
          type: string
    ReplyMessage:
      type: object
      properties:
        message:
          type: string
          example: "ok"
      required:
        - message
    Volume:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        Metadata:
          $ref: "#/components/schemas/Metadata"
        Status:
          $ref: "#/components/schemas/Status"
        Spec:
          $ref: "#/components/schemas/VolSpec"
    VolSpec:
      type: object
      properties:
        type:
          type: string
        kind:
          type: string
        volumeGroup:
          type: string
        logicalVolume:
          type: string
        size:
          type: integer
          format: int
        path:
          type: string
        osVariant:
          type: string
        persistent:
          type: boolean
    NetworkInterface:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        uuid:
          type: string
        networkname:
          type: string
        ethernet:
          type: string
        mac:
          type: string
        dhcp4:
          type: boolean
        dhcp6:
          type: boolean
        address:
          type: string
        netmask:
          type: string
        nameservers:
          type: object
          $ref: "#/components/schemas/Nameservers"
        routes:
          type: array
          maxItems: 6
          items:
            $ref: "#/components/schemas/Route"
        portgroup:
          type: string
        vlans:
          type: array
          maxItems: 4
          items:
            type: integer
            format: uint
    Nameservers:
      type: object
      properties:
        addresses:
          type: array
          maxItems: 4
          items:
            type: string
        search:
          type: array
          maxItems: 4
          items:
            type: string
    Route:
      type: object
      properties:
        to:
          type: string
        via:
          type: string
    Servers:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Server"
    Server:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        Metadata:
          $ref: "#/components/schemas/Metadata"
        Spec:
          $ref: "#/components/schemas/ServerSpec"
        Status:
          $ref: "#/components/schemas/Status"
    Status:
      type: object
      properties:
        status:
          type: integer
          format: int
        creationTimeStamp:
          type: string
          format: date-time
        deletionTimeStamp:
          type: string
          format: date-time
        lastUpdateTimeStamp:
          type: string
          format: date-time
        message:
          type: string
    Metadata:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        uuid:
          type: string
        key:
          type: string
        instanceName:
          type: string
        comment:
          type: string
    ServerSpec:
      type: object
      properties:
        cpu:
          type: integer
          format: int
        memory:
          type: integer
          format: int
        NetworkInterface:
          type: array
          maxItems: 10
          items:
            $ref: "#/components/schemas/NetworkInterface"
        Storage:
          type: array
          maxItems: 10
          items:
            $ref: "#/components/schemas/Volume"
        osLv:
          type: string
        osVg:
          type: string
        osVariant:
          type: string
        bootVolume:
          $ref: "#/components/schemas/Volume"
    VirtualNetwork:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        Metadata:
          $ref: "#/components/schemas/Metadata"
        Spec:
          $ref: "#/components/schemas/VirtualNetworkSpec"
        Status:
          $ref: "#/components/schemas/Status"
    VirtualNetworkSpec:
      type: object
      properties:
        forwardMode:
          type: string
        bridgeName:
          type: string
        macAddress:
          type: string
        stp:
          type: boolean
        ipAddress:
          type: string
        netmask:
          type: string
        dhcp:
          type: boolean
        dhcpStartAddress:
          type: string
        dhcpEndAddress:
          type: string
        nat:
          type: boolean
    IPNetwork:
      type: object
      required:
        - Id
      properties:
        Id:
          type: string
        AddressMaskLen:
          type: string
        StartAddress:
          type: string
        EndAddress:
          type: string
    IPAddress:
      type: object
      required:
        - Address
      properties:
        NetworkId:
          type: string
        IPAddress:
          type: string
        Netmask:
          type: string
        HostId:
          type: string
