name: Etcd Service Example
on: push

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    #container: bitnami/etcd:3.5.9
    # Service containers to run with `runner-job`
    #services:
      # Label used to access the service container
    #  etcd:
        # Docker Hub image
    #    image: bitnami/etcd
        #
    #    ports:
          # Opens tcp port 2379 on the host and service container
    #      - 2379:2379

    steps:
    - uses: actions/checkout@v3
    - name: Install ca-certificates
      run: |
        sudo apt update && sudo apt install -y ca-certificates
        sudo update-ca-certificates

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build pkg/config
      run: | 
        cd pkg/config
        go test -v 
        cd ../..

    - name: Build pkg/db
      run: | 
        cd pkg/db
        go test -v 
        cd ../..
