name: Etcd Service Example
on: push

jobs:
  # Label of the container job
  runner-job:
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      etcd:
        # Docker Hub image
        image: bitnami/etcd
        #
        ports:
          # Opens tcp port 2379 on the host and service container
          - 2379:2379

