name: marmot CI on self-hosted hv2
on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR || 'MARMOT CI' }}
  DEBUG: true

jobs:
  # Label of the job
  start:
    runs-on: [ self-hosted, any ]
    steps:
    - uses: actions/checkout@v5

  moodule-tests:
    runs-on: [ self-hosted, any ]
    needs: 
      - start
    if: always() 
    steps:
    - uses: actions/checkout@v5
    - name: 時間調整
      run: | 
        sleep 10

  system-tests:
    runs-on: [ self-hosted, any ]
    needs: 
      - start
    if: always() 
    steps:
    - uses: actions/checkout@v5

  packages-run-as-nonroot:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always() 
    steps:
    - uses: actions/checkout@v5
    - name: コンフィグパッケージ
      run: | 
        cd pkg/config
        make test
        cd ../..
    - name: ETCDのデータアクセス パッケージ
      run: | 
        cd pkg/db
        make test
        cd ../..
    - name: QCOW2操作 パッケージ
      run: | 
        cd pkg/qcow
        make test
        cd ../..

  packages-run-as-root:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always() 
    steps:
    - uses: actions/checkout@v5
    - name: ロジカルボリューム マネージャー 操作パッケージ
      run: | 
        cd pkg/lvm
        sudo -s make test
        cd ../..
    - name: ランナーのセットアップ
      run: |
        sudo -E env "PATH=$PATH" ./tools/setup.sh
    - name: ユーティリティ パッケージ 
      run: | 
        cd pkg/util
        sudo -s make test
        cd ../..

  package-virsh:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always() 
    steps:
    - uses: actions/checkout@v5
    - name: ランナーのセットアップ
      run: |
        sudo -E env "PATH=$PATH" ./tools/setup.sh
    - name: 仮想ネットワーク作成
      run: | 
        sudo -E env "PATH=$PATH" ./tools/setup-libvirt-networks.sh
    - name: 仮想化操作 パッケージ
      run: | 
        cd pkg/virt
        sudo -s make test
        cd ../..

  package-marmotd-volume:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: Test pkg/marmotd ボリューム機能テスト
      run: |
        cd pkg/marmotd
        sudo -s make test-volume
        cd ../..

  package-marmotd-server:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: Test pkg/marmotd サーバー機能テスト
      run: |
        cd pkg/marmotd
        sudo -s make test-server
        cd ../..

  package-marmotd-etc:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: Test pkg/marmotd ネットワーク機能テスト
      run: |
        cd pkg/marmotd
        sudo -s make test-vnet
        sudo -s make test-ipnet
        sudo -s make test-cloud-init
        sudo -s make test-timeout
        sudo -s make test-backing-store
        sudo -s make test-config
        sudo -s make test-volume-backing-store 
        cd ../..

  package-marmotd-images:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: 仮想ネットワーク作成
      run: | 
        sudo -E env "PATH=$PATH" ./tools/setup-libvirt-networks.sh
    - name: Test pkg/marmotd サーバーとイメージ機能テスト
      run: |
        cd pkg/marmotd
        sudo -s make test-server-image
        cd ../..
 
  package-marmotd-osimage:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: Test pkg/marmotd OSイメージ機能テスト
      run: |
        cd pkg/marmotd
        sudo -s make test-osimage
        cd ../..

  # Label of the job
  #marmot-daemon:
  #  runs-on: [ self-hosted, runner1 ]
  #  steps:
  #  - uses: actions/checkout@v5
  #  - name: Install ca-certificates
  #    run: |
  #      sudo apt update && sudo apt install -y ca-certificates dnsutils etcd-client
  #      sudo update-ca-certificates
  #
  #  - name: Setup for build
  #   run: |
  #      make setup
  #
  #  - name: Test pkg/marmotd 全機能テスト
  #    run: |
  #      cd pkg/marmotd
  #      sudo -s make test
  #       cd ../..

  mactl-vm-deploy-basic:
    runs-on: [ self-hosted, any ]
    needs: 
      - system-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: 仮想ネットワーク作成
      run: | 
        sudo -E env "PATH=$PATH" ./tools/setup-libvirt-networks.sh
    - name: mactlコマンドのテスト その１
      run: | 
        cd cmd/mactl
        make mactl-test
        sudo -E env "PATH=$PATH" make test0
        cd ../..
        sudo -E env "PATH=$PATH" ./tools/cleanup.sh

  mactl-vm-deploy-1:
    runs-on: [ self-hosted, any ]
    needs: 
      - system-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: 仮想ネットワーク作成
      run: | 
        sudo -E env "PATH=$PATH" ./tools/setup-libvirt-networks.sh
    - name: mactlコマンドのテスト その１
      run: | 
        cd cmd/mactl
        make mactl-test
        sudo -E env "PATH=$PATH" make test1
        cd ../..
        sudo -E env "PATH=$PATH" ./tools/cleanup.sh

  mactl-vm-deploy-2:
    runs-on: [ self-hosted, any ]
    needs: 
      - system-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: 仮想ネットワーク作成
      run: | 
        sudo -E env "PATH=$PATH" ./tools/teardown-libvirt-networks.sh
    - name: mactlコマンドのテスト その２
      run: | 
        cd cmd/mactl
        make mactl-test
        sudo -E env "PATH=$PATH" make test2
        cd ../..
        sudo -E env "PATH=$PATH" ./tools/cleanup.sh

  mactl-vm-deploy-3:
    runs-on: [ self-hosted, any ]
    needs: 
      - system-tests
    if: always()
    steps:
    - uses: actions/checkout@v5
    - name: 仮想ネットワーク作成
      run: | 
        sudo -E env "PATH=$PATH" ./tools/teardown-libvirt-networks.sh
    - name: mactlコマンドのテスト その３
      run: | 
        cd cmd/mactl
        make mactl-test
        sudo -E env "PATH=$PATH" make test3
        cd ../..
        sudo -E env "PATH=$PATH" ./tools/cleanup.sh


    #- name: Test cmd/maadm
    #  run: | 
    #    cd cmd/maadm
    #    sudo -s mkdir -p bin
    #    sudo -s chown ubuntu:ubuntu bin
    #    sudo -s chmod 755 bin
    #    sudo -E env "PATH=$PATH" make test
    #    sudo rm -fr bin
    #    cd ../..

  #cleanup-runner1:
  #  runs-on: [ self-hosted, runner1 ]
  #  needs: 
  #    - marmot-daemon
  #  if: always() 
  #  steps:
  #    - name: 各ランナーを掃除
  #      run: |
  #        pwd
  #        ls -al
  #         sudo -E env "PATH=$PATH" ./tools/cleanup.sh

  moodule-tests-end:
    runs-on: [ self-hosted, any ]
    needs: 
      - packages-run-as-nonroot
      - packages-run-as-root
      - package-virsh
      - package-marmotd-volume
      - package-marmotd-server
      - package-marmotd-etc
      - package-marmotd-images
      - package-marmotd-osimage
    if: always() 
    steps:
    - uses: actions/checkout@v5

  system-tests-end:
    runs-on: [ self-hosted, any ]
    needs: 
      - mactl-vm-deploy-basic
      - mactl-vm-deploy-1
      - mactl-vm-deploy-2
      - mactl-vm-deploy-3
    if: always() 
    steps:
    - uses: actions/checkout@v5

  final-cleanup:
    runs-on: [ self-hosted, any ]
    needs: 
      - moodule-tests-end
      - system-tests-end
    if: always() 
    steps:
    - uses: actions/checkout@v5
    - name: 最終クリーンアップ
      run: |
        sleep 1
